sql/parse/parse.go
sql/parse/parse_test.go

Changing how `show tables` statement was handled to use `sqlparser` instead of a string  comparison
Closes #6

Parse 'SHOW TABLES' statement properly

---

mem/table.go
sql/core.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/common_test.go
sql/plan/distinct.go
sql/plan/distinct_test.go
sql/plan/project_test.go
sql/type.go
sql/type_test.go

Closes #2 
This PR implements the DISTINCT SQL Node. Distinct wraps a projection and emits only rows that have not been previously seen before.
There is a common table with more than 100 rows to perform benchmarks. A Benchmark has been added for both Project and Distinct, which shows that Distinct is two orders of magnitude slower than Project. Although this is just a first approximation to have the feature, in the feature we should spend some time thinking on how to properly and efficiently implement the distinct and/or try to identify if the projection is sorted, which would eliminate the need to keep track of the hashes and make this way faster.

*: implement distinct clause

---

sql/analyzer/rules_test.go
sql/expression/star.go
sql/expression/star_test.go
sql/parse/parse_test.go

This PR adds tests for the rule that resolves the Star node and it adds a case to check the star is correctly parsed.
Also, clarifies in the docs that Star is just a placeholder node. Some methods with FIXMES have been replaced with panics, as Star methods should never be called.

sql: better coverage of star rule and clarify it's a placeholder

---

sql/expression/comparison.go
sql/expression/unresolved.go

`UnresolvedFunction` and `UnresolvedColumn` are placeholders, instead of potentially return wrong data it's preferable to panic and let the user know these methods should not be called.
This introduced an expected bug, which is that tests fail because types of the comparison children are obtained ahead of time. So I've fixed this moving that to Eval time.

sql/expression: mark as placeholder unresolved expressions

---

sql/parse/parse.go
sql/parse/parse_test.go

Fix #38 
Also, this is not inner join as said in the issue, is cross join, because INNER JOIN is not implemented right now.

sql/parse: support more than 2 tables on cross join

---

engine_test.go
sql/expression/common.go
sql/expression/function.go
sql/expression/function_test.go
sql/functionregistry.go

Fixes #42
This PR implements the substring(str, start[, length]) function with the same rules as its homonym function in MySQL.
Since Go strings are UTF8, this function does not return a direct substring `str[start:start+length]`, instead returns the substring of runes. That is, `"á"[0:1]` does not return a partial unicode glyph, but `"á"` itself.

sql/expression: implement substring function

---

sql/analyzer/analyzer.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go
sql/plan/group_by.go
sql/plan/group_by_test.go

- Use of `First` aggregation removed from `GroupBy`
- Rule added to validate `group by` statements.

Fix GroupBy

---

engine_test.go
sql/expression/common.go
sql/expression/function.go
sql/expression/function_test.go

sql/expression: implement year UDF

---

sql/expression/aggregation.go
sql/expression/alias.go
sql/expression/boolean.go
sql/expression/comparison.go
sql/expression/function.go
sql/expression/isnull.go
sql/expression/logic.go
sql/expression/star.go
sql/expression/unresolved.go
sql/plan/cross_join.go
sql/plan/describe.go
sql/plan/filter.go
sql/plan/group_by.go
sql/plan/insert.go
sql/plan/limit.go
sql/plan/offset.go
sql/plan/project.go
sql/plan/sort.go

There were some transforms that were not correctly propagating the transformation.
Also, there were some transforms that were unnecessarily verbose, so I simplified them while I was at it.

sql/(plan,expression): simplify and fix transforms

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/common_test.go
sql/plan/cross_join.go
sql/plan/filter.go
sql/plan/innerjoin.go
sql/plan/innerjoin_test.go

Closes #57
Implements the INNER JOIN node, which right now is basically a `Filter(cond, CrossJoin(left, right))` given it has no indexes whatsoever.
The only clause of the INNER JOIN implemented is the ON clause. USING does not make sense to implement until we have a proper handling of column qualifiers.
The implementation of INNER JOIN differs from the one in CROSS JOIN. While the cross join loads all the right rows in memory and iterates the left rows, the inner join creates a new iterator for each iteration of the left iterator, saving huge amounts of memory on large tables.

sql/(parse,plan): implement inner join

---

sql/analyzer/validation_rules.go
sql/core.go
sql/expression/aggregation.go
sql/plan/group_by.go

The interface `Aggregation` is not used anywhere at all. We are using the interfaces `Expression` and `AggregationExpression` instead.
I removed the old `Aggregation` interface and renamed `AggregationExpression` to just `Aggregation`.

Unified Aggregation's interfaces

---

engine.go

Engine is not implementing the `Driver` interface anymore.

Fix Engine comment

---

_example/main.go
server/handler.go
server/server.go
server/session.go

With the work done in #80 we can pass sessions around, but there is no way to tell the server to create custom sessions. This implements a Session Manager that keeps track of all the sessions and handles cancellation of sessions when connection is closed as well as a mechanism to create custom sessions using SessionBuilders.

server: implement session manager

---

sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/plan/distinct.go
sql/plan/distinct_test.go
sql/plan/group_by.go
sql/row.go

This improves the performance of the Distinct operation by two orders of magnitude (both in CPU and memory) when the result set is sorted.
Also adds an `Equals` method to `Row`, which can come in handy for some other operations.
Benchmark results:
```
pkg: gopkg.in/src-d/go-mysql-server.v0/sql/plan
BenchmarkDistinct-4          	     100	  13723600 ns/op	 2183356 B/op	  264693 allocs/op
BenchmarkOrderedDistinct-4   	   10000	    117517 ns/op	   65904 B/op	     925 allocs/op
BenchmarkProject-4           	   20000	     99851 ns/op	   65324 B/op	     913 allocs/op
PASS
ok  	gopkg.in/src-d/go-mysql-server.v0/sql/plan	5.600s
```

sql/(plan,analyzer): implement OrderedDistinct for sorted results

---

engine_test.go
example_test.go
mem/table_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go
sql/plan/tablealias.go
sql/plan/tablealias_test.go
sql/type.go

Depends on #82 
Fixes #88
Because of the way we access the fields in the rows using GetField with the index in which they appear and only by name, there was no way of knowing which field was the correct when there were multiple fields with the same name.
Now, all columns include a "Source", which is defined by the table and must match the table name (this is validated by an analyzer validation rule), so that we can identify from which table we should get the field.
One notable exception to this is TableAlias, which avoids this limitation only when its child node is not a Projection (that is, a subquery).

 sql/analyzer: resolve GetField on schemas with repeated column names 

---

sql/analyzer/filters.go
sql/analyzer/filters_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/core.go
sql/plan/filter.go
sql/plan/innerjoin.go
sql/plan/pushdown.go
sql/plan/pushdown_test.go
sql/type.go

Depends on #82 
Closes #27 
Closes #28 
Supersedes #83 
Only columns and filters that apply to a column are pushed down to that column. That is, if you have `42 > 5` that filter will not be pushed down to any table, and if you have `a.foo = 5` that filter will only be pushed down to table `a`.
If more than one table is mentioned in a filter, it's not pushed down to neither. E.g. `a.foo = b.foo` is not pushed down.
Perhaps we want the opposite and we want all filters pushed down to the table, regardless of whether it mentions the table or not?
Also, join conditions are not being pushed down as filters, should we also push those down?

sql/(plan,analyzer): implement pushdown of filters and cols

---

benchmark/tpc_h_test.go
engine_test.go
example_test.go
mem/database.go
mem/database_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/catalog_test.go
sql/core.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/ddl.go
sql/plan/ddl_test.go
sql/plan/show_tables.go
sql/plan/show_tables_test.go
sql/type.go

Also, memory DB implementation constructor now returns the sql.Database interface instead of the implementation itself.

Add CREATE TABLE DDL statement

---

engine.go
mem/database.go
mem/table.go
sql/analyzer/analyzer.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/analyzer/validation_rules.go
sql/catalog.go
sql/core.go
sql/functionregistry.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/ddl.go
sql/plan/group_by.go
sql/plan/insert.go
sql/plan/sort.go
sql/plan/unresolved.go
sql/type.go

- Use src-d/go-errors.v1 instead of src-d/go-errors.v0
- Use go-errors library instead of errors or fmt
- Unify common errors

Improve errors

---

sql/analyzer/rules.go
sql/analyzer/rules_test.go

Closes #93 
Could not reproduce the "not resolved because of node *" error message, I guess that's fixed and other errors take its place now. I found this error message that could be improved tho.

sql/analyzer: improve error message when column with no table is not found

---

sql/analyzer/rules.go
sql/analyzer/validation_rules.go
sql/core.go
sql/expression/between.go
sql/expression/common.go
sql/expression/comparison.go
sql/expression/function/substring.go
sql/expression/get_field.go
sql/expression/literal.go
sql/expression/star.go
sql/expression/tuple.go
sql/expression/unresolved.go
sql/expression/walk.go
sql/expression/walk_test.go
sql/plan/filter.go
sql/plan/group_by.go
sql/plan/innerjoin.go
sql/plan/project.go
sql/plan/pushdown.go
sql/plan/sort.go
sql/plan/values.go
sql/plan/walk.go
sql/plan/walk_test.go

Closes #106 
Closes #107 
It only diverges from the original proposal in that it adds `WalkExpressions` and `InspectExpressions` in `plan` package because of the limitation of `Expression`s not being `Node`s.

Walk the tree

---

sql/type.go
sql/type_test.go

Closes #134 
**NOTE:** because of the usage of `[]interface{}` internally, there's a side effect of implementing this type and is that arrays can be cast to tuples and vice-versa. Therefore, any function that can use arrays as input can use tuples as input (though that can be enforced inside the functions just as #35 does).

sql: add Array type

---

engine.go
sql/analyzer/analyzer.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go

Depends on #138
Related to #137 
This propagates the context throughout the analyzer, which we didn't do before and it will be needed in the next step for #137, which is actually tracing all nodes and components.

 sql/analyzer: propagate context throughout the analyzer 

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/parse/parse_test.go

Fixes #144
Even if literals were being parsed correctly as the Column in the SortFields, we were not acting accordingly on the Sort node, because it acted as a literal and not a GetField expression.
This commit adds a rule to replace the Literal expression inside the SortField Column field into an UnresolvedColumn that will get resolved as any other column in the tree. By doing this with a rule, we avoid handling this special case inside the Sort node.

sql/analyzer: replace column indexes with GetFields in SortFields

---

sql/analyzer/analyzer.go
sql/analyzer/analyzer_test.go

Some convenience methods to add rules and validation rules. Required (not required, but appending directly to the slice is a bit fragile) by the join pushdown.

sql/analyzer: add AddRule and AddValidationRule methods to analyzer

---

engine_test.go
server/context.go
sql/session.go
sql/session_test.go

As the number of dependencies inside sql.Context grows, so will the number of arguments of sql.NewContext. To avoid that, since most of them in testing and mocking are the default arguments it's more convenient to set some default values and configure them optionally using the functional options pattern to do so.

sql: implement functional options pattern for context building

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go

Fixes #153
DUAL is a special table that is used when no other table is. For example, `SELECT 1+2` becomes `SELECT 1+2 FROM DUAL`. Because it is a special table, it does not show up in `SHOW TABLES` or anything like that. For that reason, having the analyzer to resolve that table without needing that it is on the catalog means we don't have to add special checks for this case in the logic that finds tables in the catalog.

sql/analyzer: resolve DUAL table

---

.gitignore
Gopkg.lock
Gopkg.toml
_example/main.go
engine.go
engine_test.go
server/config.go
server/server.go
sql/analyzer/analyzer.go
sql/expression/function/aggregation/avg.go
sql/expression/function/aggregation/count.go
sql/expression/function/aggregation/max.go
sql/expression/function/aggregation/min.go
sql/parse/parse.go
sql/session.go

Description: https://github.com/src-d/go-mysql-server/issues/151

Opentracing

---

engine_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/core.go
sql/plan/project.go
sql/type.go

Fixes https://github.com/src-d/gitbase/issues/241
This commit introduces 2 new analyzer rules:
- `erase_projection`, which deletes redundant `Project` nodes. When a `Project`s schema is exactly the same as the schema of its child, the `Project` node is removed. For example `SELECT * FROM table` would be something like `Project -> Table`, which is converted to only `Table` now because the `Project` node is redundant.
- `reorder_projection`, which moves projected columns down the tree so that appearances of those columns in sort and filter nodes may be resolved. The way we parse the queries makes the `Project` the topmost node of the tree most of the time and `Filter` and `Sort` are always down `Project`. That makes it impossible for the analyzer to resolve the columns that are _created_ in …

sql/analyzer: resolve columns from the projection down the tree

---

sql/core.go
sql/expression/function/concat.go

Use `src-d/go-errors.v1`
Organize errors in sql/core.go

Use go-errors.v1

---

sql/catalog.go
sql/index.go
sql/index_test.go

Closes #170 
I removed the `Status() IndexStatus` from the `Index` interface, since doing that would require a `SetStatus` and I don't really think we should expose that method.

sql: implement index catalog

---

engine_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/validation_rules.go
sql/core.go
sql/expression/get_field.go
sql/plan/filter.go
sql/plan/group_by.go
sql/plan/innerjoin.go
sql/plan/project.go
sql/plan/pushdown.go
sql/plan/sort.go
sql/plan/values.go
sql/type.go

sql/analyzer: resolve correctly GetField expressions indexes

---

sql/core.go
sql/index.go
sql/index_test.go
sql/plan/create_index.go
sql/plan/create_index_test.go

It's hard to deal with `[]sql.Expression` in `IndexDriver` (due to interfaces deserialization issues in go). After meeting with @ajnavarro and @erizocosmico we decided to introduce some kind of `ID` which let us compare two expressions. In `IndexDriver` we do not need _full Expressions_, IDs are good enough. 
This PR introduce a new function `NewExpressionHash(Expression) hash.Hash` and `IndexDriver.ExpressionHashes() []hash.Hash`. A default implementation returns a _sha1_ (but we can replace it by any hash algorithm) based on `Expression.String()`. It would be also easy to map it, because all DBs use _key-value pairs_ as  `[]byte`.
It closes: https://github.com/src-d/go-mysql-server/issues/194

Replace expressions by hashes in IndexDriver

---

sql/plan/cross_join.go

Trying to update the `go-mysql-server` dependency in [gitbase](https://github.com/src-d/gitbase) I stumbled upon some test failing because of the `sql.RowIterToRows` function returning weird results.
The thing is that the `Next` method in the cross join iterator reuses the same memory addresses of the returning rows to allocate new rows in the next callings.
So when you keep that rows in a slice, like `sql.RowIterToRows` function does, you will end up with rows supposed not to be there in the slice if after the cross join iterator the rows are filtered by a filter iterator.
It seems that assigning the elements from the both side of the cross join to a new `sql.Row` fix the problem.

sql/plan: return a new instance of sql.Row in cross join iterator's next method

---

engine.go
mem/database.go
server/server.go
sql/analyzer/analyzer.go
sql/core.go
sql/expression/doc.go
sql/expression/function/aggregation/avg.go
sql/expression/function/arraylength.go
sql/parse/parse.go
sql/plan/common.go

This CL adds vanity imports to all packages to prevent importing any
given package from the wrong import path.

all: add vanity import specs

---

README.md
_example/main.go

Improve README

---

engine_test.go
mem/table.go
mem/table_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/catalog.go
sql/core.go
sql/expression/get_field.go
sql/index.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/mapping.go
sql/index/pilosa/mapping_test.go
sql/index_test.go
sql/plan/create_index_test.go
sql/plan/pushdown.go
sql/plan/pushdown_test.go

Closes #176
This commit introduces the `assign_indexes` rule, which finds expressions that are indexed and pushes them down to their respective tables. This rule works in combination with the `pushdown` rule. It simply finds indexes and combines them to wrap their table node with a placeholder node that has the indexes.
Then, is in the pushdown when the table node is wrapped with the final pushed down version with the projection, filters and indexes. These two rules work together because a `sql.Indexable` table also requires the filters and the projection to be pushed down. Since this logic is already implemented in the `pushdown` rule, this avoids repeating this complicated logic by simply delegating that work to the `pushdown` rule and only finding the indexes and combining them in …

sql/analyzer: implement a rule to assign indexes

---

sql/analyzer/analyzer.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go

sql/analyzer: lock indexes per-query and not per-lookup

---

engine_test.go
sql/parse/describe.go
sql/parse/describe_test.go
sql/parse/indexes.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/parse/util.go
sql/plan/describe.go
sql/plan/describe_test.go

sql/(parse,plan): implement describe queries

---

README.md
engine_test.go
sql/expression/function/registry.go

The `split` function was implemented but not added to the default functions to be registered.

sql/expression/function: add function split to the default functions to add to the registry

---

benchmark/tpc_h_test.go
engine.go
engine_test.go
example_test.go
server/handler_test.go
sql/analyzer/analyzer.go
sql/analyzer/analyzer_test.go
sql/analyzer/batch.go
sql/analyzer/rules_test.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go

- Move all the iteration logic from `Analyzer` to `Batch`. Now `Analyzer` has a set of Batch objects instead of a set of Rules.
- To be able to add custom rules, created an `analyzer.Builder` object. With it, you can build a custom `Analyzer` and add custom rules on specific Batches. This Batches can change depending on our necessities in the future.
- Validation rules do not exist anymore. Now they are standard rules into a Batch that iterates only once.
Closes: #141 

analyzer: execute rules in batches.

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go

If a natural join isn't replaced yet by the `resolveNaturalJoins` when the `resolveStar` rule is applied, a panic will raise if this natural join is a child of a `Project` or `GroupBy` node.
Related to https://github.com/src-d/gitbase/issues/323

sql/analyzer: fix star resolution when there are natural joins involved

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/plan/group_by.go

Fixes #248 
There are 3 cases:
- The child node has all needed columns, do nothing in that case.
- The child node has missing columns and it requires no column that was defined in the child, so move the order by below the child node.
- The child has missing columns and it requires some columns defined in the child, so make a new node from the child type below the orderby with the missing dependencies and a projection on top of it with the projected columns of the previous child.
This works both with groupby and project.

sql/analyzer: rule to resolve sort based on dependencies

---

sql/index/pilosa/driver.go
sql/index/pilosa/mapping.go
sql/index/pilosa/mapping_test.go

Writes are now only done once every 10000 rows. This improves index creation times.
pilosa uses import methods instead of queries to set bits. This occupies less memory and is faster than making batched queries.
boltdb mapping now has an extra mode of working (create mode). When this is active there's only one transaction per batch instead of one transaction per operation.
```
create index commit_hash on commits using pilosa (commit_hash);
```
| num repos | before | now |
|--------------|--|-----|
| 9 | 42 s | 5 s |
| 100 | 8 minutes | 21 s |

index/pilosa: batch boltdb and pilosa writes

---

engine_test.go
sql/analyzer/analyzer.go
sql/analyzer/rules.go

Partially solves https://github.com/src-d/gitbase/issues/326, requires some stuff on gitbase
Since the actual job of ensuring read only queries is done on the analyzer, it felt weird to add like a `SetReadOnly` or such to the `Engine`, because the rules have no access to the `Engine`, only the `Analyzer`, that's why I thought about this way of doing it, which felt like the least intrusive way of implementing this feature without going into users and permissions.

sql/analyzer: add rules for ensuring read only queries

---

sql/index/pilosa/index.go
sql/index/pilosa/mapping.go

Each next call to index iterator was searching for the bucket and creating a new transaction. Now the bucket and transaction is created only once and reused during all its life.
Previously:
```
index.Next() 5.445086ms
index.Next() 4.958599ms
index.Next() 4.597905ms
index.Next() 5.394169ms
index.Next() 5.161109ms
```
Now:
```
index.Next() 3.711µs
index.Next() 24.377µs
index.Next() 11.213µs
index.Next() 9.873µs
index.Next() 7.679µs
index.Next() 5.182µs
index.Next() 3.655µs
index.Next() 6.272µs
index.Next() 3.734µs
```
Some tests with queries:
* `create index path on files using pilosa (file_path);` (2620377 rows)
| rows returned | before | after |
| --- | --- | --- |
|160|1.34s|0.10s|
|1342|18s|6.34s|
* `create index author on commits using pilosa (commit_author_name);` (1933 rows)
| rows …

index/pilosa: speedup index iterator

---

sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/mapping.go

Caused this error when no rows were found:
```
MySQL [(none)]> select count(file_path) from files where file_path='index.goo';
ERROR 1105 (HY000): unknown error: id is nil
```

index/pilosa: do not error when key is not found

---

sql/analyzer/rules.go
sql/analyzer/rules_test.go

Related to https://github.com/src-d/gitbase/issues/365
(When this PR will be merged, a PR updating `go-mysql-server` and adding an integration test in `gitbase`  must be done to close that issue.)
When a natural join is transformed, all the nodes over the transformed node that reference some of the common columns by the right table in the join couldn't resolve them.
With this fix, all those columns resolve now to the left table in the join to be found.

sql/analyzer: fix columns in the resolveNaturalJoins rule

---

engine.go
engine_test.go
sql/expression/function/version.go
sql/expression/function/version_test.go

Implement [VERSION](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_version) udf.
usage:
```go
driver.Catalog.RegisterFunction("version", sql.Function0(function.NewVersion("0.1.1")))
```
```
mysql> select VERSION();
+---------+
| version |
+---------+
| 0.1.1   |
+---------+
1 row in set (0.00 sec)
```
Context: https://github.com/src-d/gitbase-playground/issues/184#issuecomment-402809742

add version udf

---

engine_test.go
sql/analyzer/optimization_rules.go
sql/analyzer/optimization_rules_test.go
sql/analyzer/rules.go
sql/expression/literal.go
sql/plan/empty_table.go

Closes #280
This commit adds the `eval_filters` rule to the analyzer, which evaluates all evaluable filters in `Filter` nodes and removes any unnecessary filter. If it turns out the final result of evaluating the filters is true, independently of the non-evaluable expressions, the filter node is just removed. If it's false, the filter node is removed and replaced with a special node called `Nothing` that returns an empty result set while still holding the instance of the inner node.

sql/analyzer: add rule to evaluate filters ahead of time

---

sql/analyzer/assign_indexes.go
sql/analyzer/assign_indexes_test.go
sql/analyzer/common_test.go
sql/index.go

Closes #262 
Note that multicolumn indexes aren't used for `NOT` expressions.

sql/analyzer: add negate index

---

README.md
benchmark/tpc_h_test.go
engine_test.go
example_test.go
mem/table.go
mem/table_test.go
server/handler_test.go
sql/analyzer/resolve_tables.go
sql/analyzer/validation_rules_test.go
sql/core.go
sql/plan/common_test.go
sql/plan/create_index_test.go
sql/plan/cross_join_test.go
sql/plan/distinct_test.go
sql/plan/filter_test.go
sql/plan/group_by_test.go
sql/plan/insert.go
sql/plan/limit_test.go
sql/plan/offset_test.go
sql/plan/project_test.go
sql/plan/sort_test.go
sql/plan/tablealias_test.go

We were not passing `*sql.Context` to `Insert`. For mem table is not much of a problem, but imagine a data source needs to update indexes after insert or inserts are expensive. Operation is not cancelable without passing context.

*: pass context to Insert

---

.travis.yml

Since the discussion around using dep on libraries is not yet settled I decided to just tweak the hack we already had for it to work.

travis: fix pilosa version installation to v0.9.0

---

README.md

Since we're now attached to v0.9.0, I thought it would be worth adding to the README in case anyone wants to contribute to reduce the friction as much as possible.

docs: specify caveats about pilosa version on README

---

sql/analyzer/resolve_natural_joins.go
sql/analyzer/resolve_natural_joins_test.go

Related to https://github.com/src-d/gitbase/issues/388 and https://github.com/src-d/gitbase/pull/391.
Fix to handle properly column resolution for chained natural joins.

sql/analyzer: fix resolveNaturalJoins rule for chained natural joins

---

sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go

Fixes the problem at https://github.com/src-d/gitbase/issues/400
After investigating for a bit, turns out the issue in gitbase is that since `*expression.Star` is a column that's never resolved, it always tries to resolve it. After table is squashed, we can no longer get the names to correctly qualify it.
What I did in this fix is just remove the qualification from the star when it's not necessary (which is any case where it's inside any other expression.
I'm not sure this is the best solution for this, though.

sql/analyzer: remove unnecessary qualification of star

---

sql/analyzer/index_catalog.go
sql/analyzer/index_catalog_test.go
sql/analyzer/resolve_database.go
sql/index.go
sql/index_test.go
sql/parse/indexes.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/show_indexes.go
sql/plan/show_indexes_test.go

Closes #303
This add support for `SHOW INDEX|INDEXES|KEYS FROM|IN table` following the same schema [mysql returns](https://dev.mysql.com/doc/refman/8.0/en/show-index.html). Nevertheless, the only valuable info is showed right now is the name of the existing indexes for the requested table.
Let me make a proposal to move all the `ExpressionHash` logic to the driver itself and expose in the index interface a method to retrieve the indexed expressions as text, which is the reason because of it's not possible show a better information about the indexes (we don't have a way to know directly all the expressions are indexed).
After that, the information returned by `show indexes` could be improved.

sql: add support for show indexes

---

sql/analyzer/assign_indexes.go
sql/analyzer/assign_indexes_test.go
sql/core.go
sql/index.go
sql/index/config.go
sql/index/config_test.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/lookup.go
sql/index_test.go
sql/plan/create_index.go
sql/plan/create_index_test.go
sql/plan/drop_index_test.go
sql/plan/show_indexes_test.go

Closes #305 
- Changed `Index` and `IndexDriver` interfaces to remove the use of `ExpressionHash`
- Removed all the logic related to `ExpressionHash`.
- Now the `config.yml` file for pilosa indexes doesn't store expression hashes anymore:
```yml
db: ""
table: refs
id: refs_name_idx
expressions:
- refs.ref_name
drivers:
pilosa: {}
```

sql: change Index and IndexDriver interfaces and remove ExpressionHash logic

---

sql/plan/group_by.go
sql/plan/group_by_test.go

Fixes #331 
Before:
```
go test -benchmem -run=^$ gopkg.in/src-d/go-mysql-server.v0/sql/plan -bench ^BenchmarkGroupBy$
goos: darwin
goarch: amd64
pkg: gopkg.in/src-d/go-mysql-server.v0/sql/plan
BenchmarkGroupBy/no_grouping-4         	     500	   3735067 ns/op	 2468276 B/op	   10075 allocs/op
BenchmarkGroupBy/grouping-4            	     200	   6032010 ns/op	 2386503 B/op	   41453 allocs/op
PASS
ok  	gopkg.in/src-d/go-mysql-server.v0/sql/plan	4.124s
```
Now:
```
go test -benchmem -run=^$ gopkg.in/src-d/go-mysql-server.v0/sql/plan -bench ^BenchmarkGroupBy$
goos: darwin
goarch: amd64
pkg: gopkg.in/src-d/go-mysql-server.v0/sql/plan
BenchmarkGroupBy/no_grouping-4         	    1000	   1641740 ns/op	  321972 B/op	   10033 allocs/op
BenchmarkGroupBy/grouping-4            	     300	   4580011 ns/op …
```

sql/plan: more efficient implementation of GroupBy

---

sql/analyzer/parallelize.go

This is gonna be needed for SquashedTables.
ResolvedTable embed sql.Table, so it should not change.

sql/analyzer: parallelize sql.Table, not just ResolvedTable

---

.travis.yml
Makefile
internal/regex/regex.go
internal/regex/regex_go.go
internal/regex/regex_native.go
internal/regex/regex_oniguruma.go
internal/regex/regex_test.go
sql/expression/comparison.go
sql/expression/comparison_test.go

Add support to register multiple regular expression engines. The change comes with "native" and "oniguruma". The latter has to be compiled with tag "oniguruma" to be registered.
Right now the session interface does not have possibility to set configuration variables so only one is used. "oniguruma" if it is available or native otherwise.
Fixes #341

expression: support multiple regex engines

---

sql/type.go
sql/type_test.go

Before this fix, when a nil value was returned for a column with type BLOB, it did panic.

fix: convert nil value properly for blob type

---

sql/analyzer/index_catalog.go
sql/index.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosalib/driver.go
sql/index/pilosalib/driver_test.go
sql/index/pilosalib/index.go
sql/index_test.go
sql/plan/drop_index.go
sql/plan/show_indexes.go

Closes https://github.com/src-d/go-mysql-server/issues/343
Changes:
Right now we can drop/cancel indexes in progress.
Function `IndexesByTable` returns all indexes (`NotReady` as well), so if you want to know status you have to call `CanUseIndex`. 
Delete index uses `force` flag (what cancel the context what breaks and deletes the index).
`SHOW INDEX FROM...` shows all indexes, but `NotReady` indexes have *NO* in column `Visible`, otherwise *YES*.

Drop indexes in progress.

---

sql/parse/indexes_test.go
sql/parse/util.go

Now, identifiers such as index name are `[a-zA-Z][a-zA-Z0-9_]*`. Before it was `[a-zA-Z0-9]+`

sql/parse: allow numbers in index names

---

engine.go
engine_test.go
server/context.go
server/handler.go
server/handler_test.go
sql/analyzer/process.go
sql/analyzer/process_test.go
sql/plan/create_index.go
sql/plan/drop_index.go
sql/plan/drop_index_test.go
sql/plan/processlist_test.go
sql/processlist.go
sql/processlist_test.go
sql/session.go
sql/session_test.go

Closes #371 
Summary of changes:
- Session manager, no longer tracks contexts created for queries, only sessions. Contexts are managed by the ProcessList as part of the Process.
- Pid is available from Context now, and connection id from the Session.
- trackProcess rule does no longer register the process, only attaches step information and wraps the node if needed to track completion.
- KILL correctly handled: query just kills query but keeps connection, connection drops connection and all associated queries.
- KILL connection is also tested now (using unsafe, though :( )
- DROP INDEX cannot drop indexes that are currently being created.

*: correctly handle process management using processlist

---

sql/analyzer/parallelize.go

Moving `parallelize` after `track_process` had this subtle side effect.
This is why https://github.com/src-d/gitbase/pull/489#issuecomment-423988685 is failing

sql/analyzer: check non-parallelizable nodes under QueryProcess

---

README.md

This PR fixes a discrepancy between the example snippet and the [complete example](https://github.com/src-d/go-mysql-server/blob/master/_example/main.go).
It also changes the database name in the command line example to match the example code (although I don't think it matters in this case what database name is provided).

update readme example snippet to match complete example

---

server/server.go

Probably fixes https://github.com/src-d/gitbase/issues/520
We should not have hardcoded limits so low in here. By default there should be no limits.

server: do not set timeouts by default

---

engine_test.go
sql/parse/parse.go

Closes: https://github.com/src-d/go-mysql-server/issues/418

Fix substring/2

---

sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go

Pilosa holder cannot be opened more than once. It has a channel to
signal opened state (currently unused) that is closed after the first
Open. This causes panics in the next calls:
panic: close of closed channel
The driver was using one holder for all db/tables. This called
holder.Open once per table. This works well if all indexes belong to the
same db/table but called Open several times when the indexes belong to
more than one db/table pair. Now it has a map of holders so it's only
opened once.
Related to src-d/gitbase#524

pilosa: use different holder per db/table pair

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/showcolumns.go
sql/plan/showcolumns_test.go

Depends on #417 
Closes #404 
Caveats:
- Vitess doesn't support EXTENDED, so we don't do that either
- We don't have collations, so I set as default utf8_bin, which is what we're doing

 sql: implement SHOW FIELDS statement

---

_scripts/go-vitess/LICENSE
_scripts/go-vitess/Makefile
_scripts/go-vitess/README.md

See prior PR on https://github.com/src-d/go-vitess/pull/4
While the README says that this repo is under the Apache License 2.0, no LICENSE file was found.
This PR adds the proper license file to the repo in Github format and formats the LICENSE/README links to reference the license without Markdown (as in, the file is just LICENSE, not LICENSE.md) for consistency across other srd-d repos.
Don't forget to add the copyright year and name at the bottom of the license. :smile:

Adds Proper Apache License 2.0

---

README.md
SUPPORTED.md
engine_test.go
sql/expression/function/registry.go

Register COALESCE function. Update docs. Add integration test to engine.

---

.travis.yml

Remove go-tip to do not use unnecessary Travis slots

---

sql/analyzer/optimization_rules.go
sql/analyzer/optimization_rules_test.go

The reorder projection rule recreates the projection with the table
columns and aliases. When an alias is used more than once in a
node expression, for example, a filter (`a=1 or a=2`) it is added twice.
This caused the second time to add nil as the aliases where deleted
after adding them to projections list.
Now the columns are added only once.
Fixes src-d/gitbase#546

analyzer: fix crash with aliases used multiple times

---

sql/index/pilosa/driver.go

After upgrading pilosa to the latest revision, we have holder which can be reopened.
It's also good to have a one holder per driver instead of creating new holder for every `Load`. It will also simplify a code a little bit.
Closes: https://github.com/src-d/go-mysql-server/issues/429

One pilosa holder

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/parse/variables.go
sql/plan/showvariables.go
sql/plan/showvariables_test.go
sql/session.go

Closes: https://github.com/src-d/go-mysql-server/issues/409
The PR implements:
`SHOW [global | session] VARIABLES [LIKE pattern]`
where _global_, _session_ are ignored (we copy config from `BaseSession`).
So far it supports `LIKE` condition. In the future we can also add `WHERE`

Implement SHOW VARIABLES

---

engine_test.go
sql/expression/function/aggregation/avg_test.go
sql/type.go
sql/type_test.go

Right now for `numberT` we cast all values to `Int64`. It impacts aggregation functions like AVG, MIN, MAX, etc.
This PR checks _the number_ type and cast it appropriately.
Closes: https://github.com/src-d/go-mysql-server/issues/450

For numberT cast to the sqltype.

---

engine_test.go
information_schema.go

*: add information_schema db with files and column_statistics tables

---

information_schema.go
sql/index/pilosa/index.go
sql/plan/create_index.go

sql/plan: correctly count processed index rows globally instead of per partition

---

engine_test.go
server/handler.go
sql/analyzer/assign_catalog.go
sql/analyzer/assign_catalog_test.go
sql/analyzer/readonly.go
sql/catalog.go
sql/catalog_locks_test.go
sql/catalog_test.go
sql/core.go
sql/parse/describe.go
sql/parse/indexes.go
sql/parse/lock.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/parse/util.go
sql/plan/lock.go
sql/plan/lock_test.go

*: implement LOCK and UNLOCK of tables

---

sql/session.go

sql: add timing info to span traces

---

sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/lookup.go

Closes: https://github.com/src-d/go-mysql-server/issues/472

No holder!

---

engine_test.go
sql/expression/arithmetic.go
sql/expression/arithmetic_test.go
sql/parse/parse.go
sql/parse/parse_test.go

Closes https://github.com/src-d/go-mysql-server/issues/444

sql/(parse,expression): implement unary minus

---

engine_test.go
sql/type.go
sql/type_test.go

MySQL supports multitude of formats to parse datetime data. Not all
formats are supported as some of them require changing the way of
parsing as they support any separator.
Information about datetime parsing can be found here:
https://github.com/MariaDB/server/blob/mysql-5.5.36/sql-common/my_time.c#L124
```
DESCRIPTION
At least the following formats are recogniced (based on number of digits)
YYMMDD, YYYYMMDD, YYMMDDHHMMSS, YYYYMMDDHHMMSS
YY-MM-DD, YYYY-MM-DD, YY-MM-DD HH.MM.SS
YYYYMMDDTHHMMSS  where T is a the character T (ISO8601)
Also dates where all parts are zero are allowed
The second part may have an optional .###### fraction part.
```

sql: support more timestamp formats

---

SUPPORTED_CLIENTS.md
_integration/go/mysql_test.go

Also added some helper functions to the test to retrieve a slice of string slices for easier checking.
Grafana makes another query that seems to be erroneous but does not complain:
show table columns
Fixes #467

integration: add grafana queries to go integration

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/warnings.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/parse/warnings.go
sql/plan/showwarnings.go
sql/plan/showwarnings_test.go
sql/session.go
sql/session_test.go

This PR implements _just_:
```sql
SHOW WARNINGS [LIMIT [offset,] count]
```
Note: We need to implement _collect session warnings_ (https://github.com/src-d/go-mysql-server/issues/465)
Closes https://github.com/src-d/go-mysql-server/issues/442

Show warnings - implementation

---

sql/analyzer/filters.go
sql/analyzer/filters_test.go

Fixes https://github.com/src-d/gitbase/issues/579

analyzer: fix pushdown of filters with repeated table names

---

_scripts/go-vitess/Makefile
_scripts/go-vitess/vt/log/log.go

_scripts: replace glog with logrus

---

engine_test.go
sql/expression/default.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/set.go
sql/plan/set_test.go
sql/session.go

Add support for set DEFAULT

---

_example/main.go
engine_test.go
sql/information_schema.go
sql/plan/showdatabases.go

Closes: https://github.com/src-d/go-mysql-server/issues/489

Implement information_schema.tables

---

engine_test.go
sql/parse/parse.go
sql/session.go
sql/session_test.go

Closes: https://github.com/src-d/go-mysql-server/issues/492

Implement sql_select_limit

---

_scripts/go-vitess/Makefile

Following file: https://github.com/vitessio/vitess/blob/master/go/vt/logutil/level.go
Relies on special flags set by `glog` package. If they are not set it panics. After we replaced glog by logrus (https://github.com/src-d/go-vitess/blob/master/vt/log/log.go) vitess panics.
This PR just removes `level.go` file in our vitess fork.

Do not pull vt/logutil/level.go

---

go.mod
server/handler.go
sql/session.go
sql/session_test.go

Upgrade vitess to v1.2.1

---

sql/analyzer/optimization_rules.go
sql/analyzer/optimization_rules_test.go
sql/analyzer/rules.go

sql/analyzer: add rule to avoid unnecessary casts

---

_scripts/go-vitess/Makefile

PR https://github.com/vitessio/vitess/pull/4328/files is already merged, so we don't have to delete `level.go` because it doesn't panic, anymore.

level.go doesn't panic anymore.

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/showtablestatus.go
sql/plan/showtablestatus_test.go

Fixes #530 
- Fixes parsing without FROM/IN/WHERE/LIKE
- When no database specified, only tables from current database should be used, as MySQL does.

sql/(plan,parse): fix show table status behaviour

---

auth/common_test.go
engine_test.go
server/context.go
server/handler_test.go
sql/analyzer/check_auth.go
sql/expression/function/connection_id_test.go
sql/plan/processlist.go
sql/plan/processlist_test.go
sql/processlist.go
sql/processlist_test.go
sql/session.go
sql/session_test.go

Previously it was showing server address but should be the client:
https://dev.mysql.com/doc/refman/8.0/en/processlist-table.html
Also merged client user and address as Client struct in session.

sql: process list now shows client address

---

engine_test.go
sql/analyzer/resolve_columns.go
sql/analyzer/validation_rules.go
sql/expression/function/time_test.go
sql/parse/parse.go
sql/parse/parse_test.go

Closes: https://github.com/src-d/go-mysql-server/issues/520, https://github.com/src-d/go-mysql-server/issues/524, https://github.com/src-d/go-mysql-server/issues/535

Implement group by index

---

engine_test.go
go.mod
sql/parse/parse.go

Closes https://github.com/src-d/go-mysql-server/issues/532

upgrade vitess to v1.4.0

---

sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/lookup.go

It fixes filtered and negate lookups (in the same way how it was done for regular lookup).
Thanks to this fix we may have intersect lookups with different conditions like: `a=1 AND b < 5`

Fix filtered index

---

sql/parse/parse.go
sql/parse/parse_test.go

Closes https://github.com/src-d/gitbase/issues/622
So far we don't support subqueries (for filters/conditions). This PR adds explicit error message for subqueries.

Add error for subqueries

---

sql/parse/parse.go
sql/parse/parse_test.go

Closes https://github.com/src-d/go-mysql-server/issues/553

Add explicit error when ON clause is missed for JOIN statement

---

sql/type.go

Closes https://github.com/src-d/gitbase/issues/615

Make conversion error clearer and less detailed.

---

sql/expression/comparison.go
sql/expression/like.go

First approach to close https://github.com/src-d/gitbase/issues/544

Replace one regex by pool of regex matchers.

---

sql/expression/function/soundex.go
sql/expression/function/soundex_test.go

Fix soundex type

---

README.md
SUPPORTED.md
sql/expression/function/registry.go
sql/expression/function/time.go
sql/expression/function/time_test.go

Closes #566 
Didn't add integration tests for this for obvious reasons.

function: implement NOW function

---

engine_test.go
sql/analyzer/optimization_rules.go
sql/analyzer/prune_columns.go
sql/analyzer/prune_columns_test.go
sql/analyzer/rules.go

Closes #570 
Also fixes a bug we didn't notice that didn't resolve correctly in reorder projection.

analyzer: add rule to prune unnecessary columns

---

sql/analyzer/prune_columns.go
sql/analyzer/prune_columns_test.go

There was an uncaught bug that pruned columns inside the subquery using only the used columns OUTSIDE the subquery, causing potential issues. Added a test case for this so we don't miss it again.

analyzer: correctly search for subquery used columns

---

sql/analyzer/prune_columns.go
sql/analyzer/prune_columns_test.go

Also, removes `subqueryBarrier`, as `SubqueryAlias` already acts as a barrier.
Since the subqueries are fully analyzed way before the main tree gets to prune_columns, it's important that in this last pass the field fixing is done for every part of the tree to consolidate the schema after later rules have been executed on the subquery trees.

analyzer: fix fields of subqueries too on prune_columns

---

sql/index.go
sql/index/pilosa/index.go
sql/index_test.go
sql/plan/create_index.go
sql/plan/create_index_test.go

First part of https://github.com/src-d/gitbase/issues/661
After a few attempts, I've settled with this way of handling this, since this is backwards compatible, does not introduce any breaking changes and uses existing mechanisms.
Checksum is sent to the driver using the index configuration that we were not using for anything yet. Instead of changing the API of the drivers to accept a checksum, since this is more of a temporal solution until updates are supported, I preferred to use this way.
Indexes hold the checksum value inside so they can return it. An `sql.Index` may or may not implement `sql.Checksumable`, which makes it really up to the driver to use checksums or not.
Tables may also implement `sql.Checksumable`. If a table is not checksumable, the driver will do nothing related to …

sql: use checksums to determine if indexes are outdated

---

engine_test.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go
sql/expression/case.go
sql/expression/case_test.go
sql/parse/parse.go
sql/parse/parse_test.go

sql/(analyzer,parse,expression): implement case expression

---

sql/plan/innerjoin.go
sql/plan/innerjoin_test.go

```
pkg: gopkg.in/src-d/go-mysql-server.v0/sql/plan
BenchmarkInnerJoin/inner_join-4         	   50000	     34188 ns/op	   11415 B/op	     169 allocs/op
BenchmarkInnerJoin/cross_join_with_filter-4         	   30000	     41608 ns/op	   12119 B/op	     181 allocs/op
PASS
ok  	gopkg.in/src-d/go-mysql-server.v0/sql/plan	3.795s
```

sql/plan: speed up InnerJoin iterator

---

sql/index/pilosa/index.go
sql/index/pilosa/lookup.go
sql/index/pilosa/lookup_test.go

sql/index/pilosa: return all index ids in lookups

---

engine_test.go
sql/session.go

Fixes #564 
I added `READ UNCOMMITED` because it's what's most similar to what we do (no transactions at all).
> `READ UNCOMMITTED`
> 
> SELECT statements are performed in a nonlocking fashion, but a possible earlier version of a row > might be used. Thus, using this isolation level, such reads are not consistent. This is also called a dirty read. Otherwise, this isolation level works like READ COMMITTED.

sql: add transaction_isolation default value

---

sql/plan/innerjoin.go

This is why the PR updating go mysql server on gitbase failed. What I don't know is why it only failed in one test 🤔

sql: fix row construction in innerJoinIter

---

sql/analyzer/process.go
sql/analyzer/process_test.go

Closes https://github.com/src-d/gitbase/issues/679
Because subqueries are analyzed as if they were a whole independent
query QueryProcess nodes were added to them. That caused that as
soon as a subquery finished, the process were marked as done. As a
result, some queries could error with "context canceled", as the
context of the query had already been canceled.
This fix removes the QueryProcess nodes from any subquery and makes
sure only the root node is wrapped in a QueryProcess.

sql/analyzer: remove QueryProcess nodes from subqueries

---

server/handler.go

server: return empty results when query is KILL

---

sql/expression/function/ceil_round_floor.go
sql/expression/function/coalesce.go
sql/expression/function/concat.go
sql/expression/function/concat_ws.go
sql/expression/function/json_extract.go
sql/expression/function/logarithm.go
sql/expression/function/rpad_lpad.go
sql/expression/function/substring.go
sql/functionregistry.go

sql: better errors for invalid argument number

---

sql/plan/innerjoin.go
sql/plan/innerjoin_test.go

This exposes the env var `EXPERIMENTAL_IN_MEMORY_JOIN` to enable the in-memory join feature, which causes inner joins to be performed in memory, which is significantly faster.
This way, clients can decide if they should enable in memory joins or not depending on their environment. If they can trade memory usage for speed this is orders of magnitude faster (specially for computationally expensive inner join branches) than the regular inner joins.
These are the benchmarks:
```
goos: darwin
goarch: amd64
pkg: gopkg.in/src-d/go-mysql-server.v0/sql/plan
BenchmarkInnerJoin/inner_join-4         	   50000	     33170 ns/op	   10618 B/op	     144 allocs/op
BenchmarkInnerJoin/in_memory_inner_join-4         	  100000	     21972 ns/op	    7322 B/op	      84 allocs/op …
```

add experimental optional feature to use in memory joins

---

SUPPORTED_CLIENTS.md
_integration/python-sqlalchemy/Makefile
_integration/python-sqlalchemy/requirements.txt
_integration/python-sqlalchemy/test.py
sql/plan/show_create_table.go
sql/plan/show_create_table_test.go

Fixes https://github.com/src-d/go-mysql-server/issues/594

Support SQLAlchemy syntax for show create table

---

engine_test.go
sql/expression/comparison.go
sql/expression/comparison_test.go

Fixes https://github.com/src-d/go-mysql-server/issues/606

Check if regexp matcher is nil.

---

engine_test.go
sql/session.go

Fixes https://github.com/src-d/go-mysql-server/issues/600
`ClearWarnings`  rule will be execute after every query, but physically it will clear warnings if the query finished with success (when number of warnings didn't change). In other words `SHOW WARNINGS` will show all warnings till you run correct query.

Clear warnings just after successful query.

---

sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go
sql/analyzer/rules.go

Fixes #590 
Since this is just a SQL syntax issue finally I've just added a new rule to check the aliases usage at the beginning of the analysis phase that runs once before the default rules. This way it doesn't interfere with the transformations made by the rest of the rules.

sql/analyzer: fix use of declared aliases in the same projection

---

server/handler.go

Fix KILL to try to kill by the query ID instead of connID

---

sql/index.go

Perf: Avoid call to Checksum if there are no indexes.

---

sql/plan/exchange.go
sql/plan/exchange_test.go

Closes: https://github.com/src-d/go-mysql-server/issues/625

recover panic for partitions

---

go.mod
go.sum
sql/index/pilosa/iterator.go
sql/index/pilosa/mapping.go

Closes https://github.com/src-d/go-mysql-server/issues/614

go.etcd.io/bbolt v1.3.2

---

engine_test.go
sql/analyzer/resolve_orderby.go
sql/plan/group_by.go
sql/plan/group_by_test.go

Closes #630 
This fixes 2 problems:
- Not supporting arbitrary expressions in grouping
- Not taking into account the children of the groupby expressions when reordering the projections underneath

allow all expressions in grouping, resolve orderby expressions

---

server/handler.go
server/handler_test.go
sql/processlist.go

Fixes https://github.com/src-d/go-mysql-server/issues/635

KILL query always takes processlist_id

---

server/handler.go

Depending on the field type, we must add a specific charset to avoid client errors. If the charset was 0, JDBC clients changed blob types to varchar ones, because the charset was not set to binary.

Add charset to fields

---

sql/plan/innerjoin.go
sql/plan/innerjoin_test.go

Fixes #577
Because we do not have a way to estimate the cost of each side of
a join, it is really difficult to know when we can compute one in
memory. But not doing so, causes inner joins to be painfully slow,
as one of the branches is iterated multiple times.
This PR addresses this by ensuring that if the right branch of the
inner join fits in memory, it will be computed in memory even if
the in-memory mode has not been activated by the user.
An user can set the maximum threshold of memory the gitbase server
can use before considering the joins should not be performed in
memory using the `MAX_MEMORY_INNER_JOIN` environment variable or
the `max_memory_joins` session variable specifying the number of
bytes. The default value for this is the half of the available
physical memory on the …

plan: compute all inner joins in memory if they fit

---

engine_test.go
sql/analyzer/aggregations_test.go
sql/expression/function/aggregation/count.go
sql/expression/function/aggregation/count_test.go
sql/plan/group_by_test.go

Closes https://github.com/src-d/go-mysql-server/issues/642

Make count int64 function

---

engine_test.go
go.mod
go.sum
sql/analyzer/assign_indexes.go
sql/analyzer/assign_indexes_test.go

Fixes https://github.com/src-d/go-mysql-server/issues/639
Collect projection aliases and pass down to `IndexByExpression`

Check projection aliases when assigned to index.

---

sql/analyzer/pushdown.go
sql/index/pilosa/driver.go
sql/plan/cross_join.go
sql/plan/exchange.go
sql/plan/exchange_test.go
sql/plan/innerjoin.go
sql/plan/process.go

This PR is the second part of https://github.com/src-d/gitbase/issues/765

Close iterators

---

README.md
internal/regex/regex_go.go
internal/regex/regex_oniguruma.go
internal/regex/regex_test.go

- Adds a build tag for oniguruma.
- Removes the existing one for Go's regex.
- Updates the README removing references to oniguruma.

Add build, tag for oniguruma, remove for mysql_go_regex, update README

---

ARCHITECTURE.md
CONTRIBUTING.md

docs: document the architecture of the project

---

sql/plan/show_create_table.go
sql/plan/show_create_table_test.go

Signed-off-by: Máximo Cuadros <mcuadros@gmail.com>
As seen in MySQL the types in a SHOW CREATE TABLE result should be written lowercase. 
This is a requirement to make work properly SQLAlchemey, you can test the current issues with this small script:
```python
import sqlalchemy
from sqlalchemy import inspect
engine = sqlalchemy.create_engine('mysql+pymysql://root:@127.0.0.1:3306/mydb')
with engine.connect() as conn:
inspector = inspect(engine)
cols = inspector.get_columns("commits", "gitbase")
```
Result:
```
✗ gitbase (master) ✗ python foo.py
/usr/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'repository_id'
"Did not recognize type '%s' of column '%s'" % (type_, name) …
```

plan: types in lowecase on SHOW CREATE TABLE

---

sql/parse/parse_test.go
sql/parse/show_create.go
sql/parse/show_create_test.go

Fixes #662
Table names in SHOW CREATE TABLE may be qualified with the database
name. This PR adds support for optional database qualifier on SHOW
CREATE TABLE statement.

sql/parse: allow qualified table names on SHOW CREATE TABLE

---

sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/iterator.go
sql/index/pilosa/lookup.go
sql/index/pilosa/mapping.go
sql/index/pilosa/mapping_test.go
test/mem_tracer.go

sql/index/pilosa: parallelize index creation

---

README.md

Depends on #669 
In order to make chunks of the go-mysql-server documentation
copyable to gitbase using automation, we need to introduce some
markers in certain sections we might want to extract.
Also, to have a nicer format environment variables and functions
have been converted to a table.

 docs: nicer format for functions and vars in docs, add markers

---

README.md
SUPPORTED.md
engine_test.go
sql/expression/function/registry.go
sql/expression/function/tobase64_frombase64.go
sql/expression/function/tobase64_frombase64_test.go

Another low hanging fruit, adds MySQL's FROM_BASE64 and TO_BASE64 functions.
Fixes #549.

Added from_base64 and to_base64

---

README.md
sql/expression/function/registry.go

Signed-off-by: Máximo Cuadros <mcuadros@gmail.com>

sql/expression: new dayofmonth function (alias of day)

---

README.md
SUPPORTED.md
engine_test.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go
sql/expression/arithmetic.go
sql/expression/arithmetic_test.go
sql/expression/function/date.go
sql/expression/function/date_test.go
sql/expression/function/registry.go
sql/expression/interval.go
sql/expression/interval_test.go
sql/parse/parse.go
sql/parse/parse_test.go

Fixes #663
This PR introduces a few new features:
- Correctly parsing interval expressions.
- Allow using the + and - operators to subtract from and add to
dates. e.g. `'2019-04-10' - INTERVAL 1 DAY`.
- New `DATE_ADD` function, which is essentially the same as
`DATE + INTERVAL`.
- New `DATE_SUB` function, which is essentially the same as
`DATE - INTERVAL`.
- Validation rule to ensure intervals are only used in certain
specific places, such as DATE_SUB, DATE_ADD, + and -. Using it
anywhere else is not valid SQL, but vitess does not catch those
errors. Plus, even if it's an expression for convenience, its
`Eval` method is a stub and panics, so it should not be used
unless it's in an expression that knows how to deal with intervals.

sql: add support for intervals, DATE_SUB and DATE_ADD

---

server/handler.go
server/handler_test.go

Before, there was an incorrect comparison to check whether the
field was a blob or not. That resulted in all fields, including
blobs, having the UTF8 charset. Now all fields have UTF8 charset
except for BLOBs, which have binary charset.
Also, a test has been added to ensure a correct behaviour.

server: correctly set binary charset on blob fields

---

sql/index.go
sql/plan/drop_index.go
sql/plan/drop_index_test.go

Fixes #674
Status of the index was not being correctly checked, so outdated
indexes could not be dropped.
Also, the message stating you could drop the index was not printing
correct SQL, not it does.

sql/plan: make sure outdated indexes can be dropped

---

engine_test.go
sql/analyzer/prune_columns.go
sql/analyzer/resolve_columns.go
sql/expression/function/time.go

Fixes #675
When there was an alias with the same name as a column in a table,
the column was qualified with the table instead of referencing the
alias.

sql/analyzer: correctly qualify aliases with the same name as col

---

go.mod
go.sum

`jaeger-client-go` is not compatible with `jaeger-lib` 2.0.0 that was set in `go.mod`. Now uses 1.5.0 that is compatible and is the one in pilosa `go.mod`.
With this change gitbase is able to use `go-mysql-server` with `go.mod`.
This problem is mentioned here:
https://github.com/jaegertracing/jaeger-client-go/issues/363#issuecomment-473656998

Fix jaeger-lib dependency

---

sql/expression/function/json_extract.go
sql/expression/function/json_extract_test.go

In the current implementation a query stops to be executed when one of the rows is empty or doesn't fit the json path expression, this PR allows any failure on the query to a value, but fails on a wrong expression.

sql/expression: relaxed json_extract

---

sql/index/pilosa/driver.go
sql/index/pilosa/index.go
sql/index/pilosa/iterator.go
sql/index/pilosa/lookup.go
sql/index/pilosa/mapping.go
sql/index/pilosa/mapping_test.go

This PR refactors interaction with mapping. After we introduced parallel index creating, mapping became a bottleneck.
To avoid locking on boltDB write sync, we create a mapping file per partition (because we parallelized index creation per partition).
It fixes https://github.com/src-d/go-mysql-server/issues/676

Make mapping per partition

---

engine_test.go
sql/analyzer/resolve_columns.go

Because aliases on the topmost project or groupby were checked using
plan.InspectExpressions, it did so recursively. That was not the
intended behaviour, since it could find other aliases in a subquery
or other nodes down the tree.
Instead, now only the expressions of the project or groupby are
checked.

sql/analyzer: only check aliases to qualify in the topmost project

---

_scripts/go-vitess/README.md
engine_test.go
go.mod
go.sum
sql/parse/parse.go

Closes https://github.com/src-d/go-mysql-server/issues/652

Support SHOW SCHEMAS (upgrade vitess to v1.6.0)

---

engine_test.go
sql/analyzer/resolve_columns.go
sql/analyzer/resolve_having.go
sql/analyzer/resolve_having_test.go
sql/analyzer/rules.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/having.go
sql/plan/having_test.go

Closes #56
This PR adds support for the HAVING SQL clause, that allows
filtering rows and has support for aggregation functions.
For this, the following changes have been made:
- New `Having` node, which is essentially a Filter, but it is
a different node for the purpose of differentiating between the
two of them during the analysis phase.
- Having is now parsed.
- A new rule for resolving the Having node has been added. Because
of the way aggregations are executed (only inside a GroupBy node)
it is not possible to execute them in any other node that's not a
GroupBy. For this reason, this rule pushes down any aggregation
on a Having node to its child, which is the GroupBy node. If
the same aggregation is already done on the GroupBy, nothing will
be added and the aggregation on the Having …

sql: implement HAVING clause

---

auth/common_test.go
mem/table.go
mem/table_test.go
sql/analyzer/optimization_rules.go
sql/analyzer/prune_columns.go
sql/analyzer/pushdown.go
sql/catalog.go
sql/expression/comparison.go
sql/expression/function/ceil_round_floor.go
sql/expression/function/concat.go
sql/expression/function/concat_ws.go
sql/expression/function/time_test.go
sql/expression/like.go
sql/expression/unresolved.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/lookup.go
sql/parse/lock.go
sql/parse/parse.go
sql/parse/show_create.go
sql/plan/create_index.go
sql/plan/exchange_test.go
sql/plan/innerjoin.go
sql/plan/limit_test.go
sql/plan/resolved_table.go
sql/plan/walk.go

Fixes #686 except for a false positive (bug?) in the nilness tool.

Some vet tools fixes

---

engine_test.go
sql/analyzer/resolve_orderby.go

Fixes https://github.com/src-d/go-mysql-server/issues/691
Is there any better place to resolve this functions/expressions for `order by`?
So far I resolve `order by` with literals which exist in schema.

Try to order by function

---

engine_test.go
sql/analyzer/convert_dates.go
sql/analyzer/convert_dates_test.go
sql/analyzer/rules.go
sql/expression/arithmetic.go
sql/expression/convert.go
sql/expression/function/date.go
sql/type.go

Fixes https://github.com/src-d/go-mysql-server/issues/698

 sql/analyzer: wrap all time and date expressions with convert

---

engine_test.go
sql/analyzer/convert_dates.go
sql/analyzer/convert_dates_test.go
sql/analyzer/rules.go

Fixes required to work on gitbase. It was caught there because there are way more complex queries in the gitbase test suite.
Still needs some fixes to work on gitbase, because squash rule works a bit weirdly with this.

sql/analyzer: alias projected columns wrapped in converts

---

engine_test.go
sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go
sql/plan/sort.go

qualify_columns rule has been a source of bugs for quite a long time
due to the way we used to look for columns. Before, we looked for
all available schemas in all the tree of a query (excluding subqueries).
This required a lot of exceptions and treatments for special cases
that have been added over time in order to patch the bugs that kept
appearing.
It had special cases for aliases, for GroupBy, etc that kept complicating
the code and making the rule harder to follow and confusing.
This refactor simplifies the logic of the rule and treats all nodes
in the exact same way so it's simpler, more obvious and easier to
reason about.
Now, a node only has knowledge of the columns (aliases or not) defined
until it reaches the first Project, GroupBy, ResolvedTable or subquery
in each branch of …

sql/analyzer: refactor and fix bugs in qualify_columns rule

---

engine_test.go
sql/expression/function/json_extract.go
sql/type.go
sql/type_test.go

Fixes #709
When a string containing JSON (e.g. `{"a": 1, "b": true}`) is passed
to JSON.Convert, it only did `json.Marshal`, so it was marshalled as
a string (e.g. `"{\"a\":1,\"b\":true}"`), which made it impossible
to use a string with JSON_EXTRACT, which would only receive the
string.
Now, JSON.Convert does a first check for strings. If it can be
unmarshalled into JSON, then that JSON is marshalled and returned.
Otherwise, it's a string and marshalled as such.

sql: do not marshal strings containing JSON as a string in convert

---

sql/analyzer/resolve_columns.go

Friday night this possible bug came to my mind, but PR was merged because I got a chance to fix it tomorrow 😅 
Because of how plan.Inspect works, whenever a table is found in a branch the other branches are not inspected anymore. Instead, doing recursive calls all branches are visited.

sql/analyzer: do not use plan.Inspect to find available tables

---

server/context.go
server/handler.go

Could panic with "concurrent map write" error

server: guard sessions access in mutex

---

server/handler.go
server/handler_test.go
sql/plan/processlist.go
sql/plan/processlist_test.go
sql/processlist.go
sql/processlist_test.go

Related to: https://github.com/src-d/gitbase/issues/817
Right now:
- `SHOW PROCESSLIST` lists all running processes where `Id` column contains `CONNECTION_ID`.
- `KILL QUERY connection_id` kills all queries for `connection_id`, but does not close the connection.
- `KILL [CONNECTION] connection_id` terminates all running queries for `connection_id`, and closes the connection.

Make PROCESSLIST and KILL compatible with MySQL

---

README.md
engine_test.go
sql/expression/function/length.go
sql/expression/function/length_test.go
sql/expression/function/registry.go

sql/expression/function: implement char_length and length functions

---

engine_test.go
sql/expression/boolean.go
sql/expression/boolean_test.go
sql/type.go

Fixes: https://github.com/src-d/go-mysql-server/issues/726

Make boolean expression compatible with MySQL

---

sql/parse/parse_test.go
sql/parse/util.go

Fix parsing of quoted identifiers in SHOW CREATE TABLE queries

---

engine_test.go
server/handler.go
sql/analyzer/resolve_generators.go
sql/analyzer/resolve_generators_test.go
sql/analyzer/rules.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go
sql/expression/function/explode.go
sql/expression/function/registry.go
sql/generator.go
sql/generator_test.go
sql/plan/generate.go
sql/plan/generate_test.go
sql/type.go
sql/type_test.go

This pull request implements the EXPLODE expressions and generators,
which are used together to provide generation of rows based on a
column or expression that can yield multiple values.
For this, there have been some quite core changes:
- SQL method of sql.Type now returns the sqltypes.Value and an error.
This avoids panics in this method. Since generators can yield errors
it's better to just return an error and not just kill the server.
- Array type can now internally handle either arrays or generators,
making it transparent for the user. If it's used in an EXPLODE
expression, the generator will be used. Otherwise, it will be
converted automatically to an array and used without the user even
knowing what happened behind the scenes. That way, we don't need
yet another type to represent …

sql: implement EXPLODE and generators

---

go.mod
go.sum

We should be able to switch back to _MariaDB connector_.

Upgrade vitess to v1.8.0

---

sql/type.go
sql/type_test.go

Will fix https://github.com/src-d/gitbase/issues/878
Apparently, we've been handling nulls the wrong way all along when converting data to send to MySQL.

sql: correctly handle nulls in SQL type conversion

---

engine_test.go
sql/expression/function/explode.go

Will fix https://github.com/src-d/go-mysql-server/issues/755

function: correctly transform up explode nodes

---

engine_test.go
sql/core.go
sql/plan/filter.go
sql/type.go

Part of the fix for https://github.com/src-d/gitbase/issues/902
The idea is to use `EvaluateCondition` as a common logic for filtering in both gitbase squashed tables and go-mysql-server.
Right now, in go-mysql-server we just check the result `== true`, which not only is not correct but is not consistent with how gitbase does it.
In gitbase we use `sql.Boolean.Convert`, but by definition the convert method of boolean can't handle some types.
That's why I added some helper function for this with the type coercion logic that we can also reuse on gitbase.

sql: use custom boolean coercion logic in condition evaluation

---

sql/core.go
sql/core_test.go

Fixes #770
- Fix panic when float32 is evaluated
- Fix int32, int16, uint64... evaluations. Now the equality is done
correctly.
- Added string evaluation.
Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

Add test to EvaluateCondition function

---

engine_test.go
sql/expression/function/arraylength.go
sql/expression/function/arraylength_test.go

function: make array_length not fail with literal null

---

sql/expression/function/nullif_test.go
sql/expression/literal.go
sql/expression/tuple_test.go
sql/type.go
sql/type_test.go

Part of the fix for: src-d/gitbase/issues/824 (the missing part is using it on the columns / types of gitbase where superset expects varchars).
This adds `VarChar` as an specific type. As happens with `Array`, it's a parametrized type that will be returned by a function with a specific length. It is convertible from and to `Text` and `string` and will return true for `IsText` so it should work for all functions using `Text`.
There is a "TO-DO" comment I added in the `NewLiteral` function, any suggestion is welcomed:
```go
// TODO(juanjux): we should probably check here if the type is sql.VarChar and the
// Capacity of the Type and the length of the value, but this can't return an error
```

Varchar type

---

engine_test.go
sql/analyzer/resolve_having.go
sql/analyzer/resolve_having_test.go
sql/plan/limit.go
sql/plan/offset.go

Fixes #764
This one solves all the cases I could come up with. Now having group by immediately under the having is not necessary and there can be any number of nodes in between them.

sql/analyzer: fix having resolution

---

_integration/go/mysql_test.go
engine_test.go
server/handler.go
sql/session.go
sql/type.go
sql/type_test.go

Fixes #779 
Fixing this, connecting from MySQL client broke. After much debugging, turns out it was because `@@version` and `@@version_comment` didn't exist (and thus, they were null), but the client was expecting something there. I just added both, but left them empty and the problem goes away.

sql: fix how nulls are sent to clients

---

engine_test.go
sql/analyzer/optimization_rules.go
sql/expression/case.go

sql/expression: correctly evaluate conditions in CASE

---

README.md

fix build status link inside the README.md: travis-ci.org -> travis-ci.com
Signed-off-by: lwsanty <lwsanty@gmail.com>

README.md -> fix build status link

---

sql/type.go
sql/type_test.go

Using `SQL` method of a value of type `Array(JSON)` produces the following:
```
[chunk of bytes, chunk of bytes, ...]
```
With this fix, it produces:
```
[proper json, proper json]
```
This bug is blocking the pushdown of `commit_file_stats` on https://github.com/src-d/gitbase-spark-connector-enterprise/issues/86

sql: fix SQL method for arrays of JSON

---

server/context.go
sql/expression/function/sleep.go

Make Sleep check for cancelled context every second

---

README.md
engine_test.go
sql/expression/function/regexp_matches.go
sql/expression/function/regexp_matches_test.go
sql/expression/function/registry.go

function: implement regexp_matches

---

README.md
SUPPORTED_CLIENTS.md

- Change all functions descriptions in README.md to be consistent. I decided to stick to the lower-case present-tense style, as each row is easily read as `Function X returns/changes/adds... Y`. This is opinionated (consistency should be not), so I'm ok discussing the best style and changing it again once we agree on one.
- Fix typos in supported_clients.md.

Fix typos and make style consistent

---

internal/sockstate/netstat.go
internal/sockstate/netstat_darwin.go
internal/sockstate/netstat_linux.go
internal/sockstate/netstat_windows.go
internal/sockstate/sockstate.go
server/handler.go

Fix for non linux OS build

---

README.md
auth/audit_test.go
auth/common_test.go
auth/native_test.go
auth/none_test.go
engine_pilosa_test.go
engine_test.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/iterator.go
sql/index/pilosa/lookup.go
sql/index/pilosa/lookup_test.go
sql/index/pilosa/mapping.go
sql/index/pilosa/mapping_test.go

[Pilosa](https://github.com/pilosa/pilosa/) makes use of the following call which does not work on Windows:
https://github.com/pilosa/pilosa/blob/bc9747cc0f19702d9753de7ea9375d8311dfc706/syswrap/mmap.go#L53
This causes any files that refer to Pilosa to fail compilation, which in turn causes builds for this project to also fail.

Removed pilosa-dependent files from Windows compilation

---

sql/expression/like.go
sql/expression/like_test.go

Fixes #814
The problem here was that we converted [the `LIKE` pattern into a regex](https://github.com/src-d/go-mysql-server/blob/128924aa3c/sql/expression/like.go#L118-L153) and used one of the regex engines (the standard go regexp package, or oniguruma) to try to match the string from the input row. The regex was built by enclosing the `LIKE` pattern between `^` and `$` (so if the pattern was `text`, the regexp would be `^text$`). But, at least in the standard go regexp package, `^` and `$` match the beginning and the end of the text, not of the line, and the dot `.` matches any character that is not a new line character. That is, if the `LIKE` pattern is `%text%`, then the resulting regex, `^.*text.*$`, will match anything that contains the substring text and that does not contain any …

Convert LIKE patterns to specific Go regexes

---

engine_test.go
sql/parse/parse.go
sql/plan/insert.go
sql/type.go

I found some bugs for INSERT statements, and implemented a few tests as well (some specific to the bug fixes, others for general INSERT testing).
One bug dealt with integer values greater than an INT64. By default, all numbers are parsed to INT64, meaning that a column with type `sql.Uint64` cannot actually hold the entire range. I added another check that only attempts to parse as a UINT64 in the event that the INT64 parsing fails.
Another bug dealt with the absence of columns in an INSERT statement. For example: `INSERT INTO tablename VALUES ...` would parse as an empty column list, rather than the entire column list. This behavior has been fixed.
Another bug dealt with a mismatch between the number of columns supplied and the number of values supplied for an INSERT statement. This has …

Fixed INSERT bugs, added UINT64 support, and added tests

---

engine_test.go

References https://github.com/src-d/go-mysql-server/issues/814 and https://github.com/src-d/go-mysql-server/pull/817
The test as was submitted in the patch file, but applied to the current `master`.

Added LIKE test with newlines

---

engine.go
engine_test.go
memory/table.go
sql/analyzer/pushdown.go
sql/core.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/delete.go
sql/plan/insert.go

This PR is a follow-up to https://github.com/src-d/go-mysql-server/pull/822 and includes that commit's changes as well.
Looking over the [MySQL REPLACE documentation](https://dev.mysql.com/doc/refman/8.0/en/replace.html), I see that it mentions a REPLACE being either a DELETE then INSERT, or just an INSERT. I figured that there were two ways to implement this: as another interface with a unique function (`Replacer` with a `Replace` function for example), or by leveraging the already-included `Insert` and `Delete` functions from their respective interfaces. I decided to go with the latter option for the below reasons.
One point is in the reduction of code needed for someone wanting to implement the library. The more that the framework handles (without appreciable loss of freedom), the …

Implemented REPLACE

---

internal/sockstate/netstat_darwin.go
internal/sockstate/netstat_linux.go
internal/sockstate/netstat_windows.go
internal/sockstate/sockstate.go
server/handler.go
server/handler_test.go

- Also parse `/proc/net/tcp6` because go will bind to it (too) on `Listen()`  if TCP v6 is enabled on the system, and then the socket will only show on `/proc/net/tcp6`. This fixes #821.
- Fail on all kinds of closed sockets, even if they were closed correctly, before the query completion, thus ensuring that the query is cancelled.
- Two explicit channel closings to ensure the goroutines exit ASAP.

Also check sockets bind to tcp6 and fail on all closed sockets

---

_integration/go/mysql_test.go
engine_test.go
sql/parse/parse_test.go
sql/type.go
sql/type_test.go

This PR adds support for two MySQL types: CHAR and DATETIME.
The former shares much of its behaviour with VARCHAR, whereas the latter is similar to DATE, so I have refactored the tests for the older types to test also the new ones.
Fixes #807.

Add CHAR and DATETIME types support

---

sql/type.go
sql/type_test.go

This bug was discovered while creating https://github.com/src-d/go-mysql-server/pull/832, and is required for one of the tests in that PR to pass.
Null values weren't being handled in most of the value comparison code, and was causing errors for valid queries. This PR fixes those issues.

Fixed null errors during value comparisons

---

sql/plan/exchange.go

plan: fix race conditions in Exchange node

---

sql/core.go
sql/plan/delete.go

I had thought that I rebased the typo changes into the [REPLACE PR](https://github.com/src-d/go-mysql-server/pull/825) from the [DELETE PR](https://github.com/src-d/go-mysql-server/pull/822) and that those were included in the merge, but apparently I did not! I apologize for the lack of diligence on my part.

Fixed a few typos for the DELETE implementation

---

engine_test.go
sql/analyzer/resolve_orderby.go

Fixes #813 
It turns out there was a case in which a sort node could be removed

analyzer: do not erase sort node when pushing it down

---

sql/plan/show_create_table.go
sql/plan/show_create_table_test.go

Fixes https://github.com/src-d/gitbase/issues/962
It solves a compatibility issue with SQLAlchemy, as it did not return
the types the same way MySQL does.

plan: return types in lowercase in SHOW CREATE TABLE

---

engine_test.go
sql/analyzer/optimization_rules.go
sql/analyzer/optimization_rules_test.go

Related to https://github.com/src-d/gitbase/issues/976

analyzer: only optimize distinct for sorts where first column is in schema

---

engine.go
engine_test.go
memory/table.go
sql/analyzer/pushdown.go
sql/core.go
sql/expression/set.go
sql/parse/parse.go
sql/plan/update.go

Notice: one of the tests will fail until https://github.com/src-d/go-mysql-server/pull/831 is merged in, as it is required to fix one of the bugs that that test catches.
This is an implementation of UPDATE, which brings with it a new interface. Unlike the other interfaces, this one supplies two rows, the original row, and the updated row. This decision was made so that implementations that rely on primary keys can have access to the old primary key if need be.
~Besides the big change, I've also caught a bug where supplying a non-existent column to ORDER BY will cause the query to still succeed, while ignoring the ORDER BY clause. Testing against MySQL showed that an error is the proper behavior, and this has been corrected. Since the change was small, I added it here rather than making an …

Implemented UPDATE

---

engine_test.go
memory/database.go
memory/database_test.go
sql/core.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/ddl.go
sql/plan/ddl_test.go
sql/type.go
sql/type_test.go

Implemented DROP TABLE. Also:
* 24-bit integers
* Primary key attribute for columns
* Deprecated Alterable in favor of TableCreator. Primary difference is the new interface takes a context argument.

Drop / create table

---

engine_test.go
sql/information_schema.go

sql: information schema column types should be lowercase

---

engine_test.go
server/context.go
sql/analyzer/process.go
sql/session.go

sql: finish root span of the query

---

.travis.yml

Cosmetic change to make the travis build matrix more clear.
See the difference between this build: https://travis-ci.com/src-d/go-mysql-server/builds/133233668
and a previous one: https://travis-ci.com/src-d/go-mysql-server/builds/133029886

Add names to travis tests

---

sql/analyzer/process.go
sql/plan/process.go
sql/plan/process_test.go
sql/processlist.go

This is a proposal to add some more information to the `SHOW PROCESSLIST` output.
It adds a counter for each active partition. A partition gets removed from the list when it finishes.
This is how it looks:
```
$ mysql -u root -h 127.0.0.1 -P 3306 gitbase --execute "show processlist"
+------+------+-----------------+---------+---------+------+------------------------------------------------------------------+-----------------------+
| Id   | User | Host            | db      | Command | Time | State                                                            | Info                  |
+------+------+-----------------+---------+---------+------+------------------------------------------------------------------+-----------------------+
|  395 | root | 127.0.0.1:35250 | gitbase | query   |    2 …
```

Add progress for each partition in SHOW PROCESSLIST

---

engine.go
server/handler.go
sql/core.go
sql/plan/create_index.go

Fix #857.
The code in #806 added a context cancel call when the query handle finishes, https://github.com/src-d/go-mysql-server/blob/68b087cfd6d30a8d711e1f686da60bd80c54f93b/server/handler.go#L117
For an async index creation the driver is called in a goroutine https://github.com/src-d/go-mysql-server/blob/68b087cfd6d30a8d711e1f686da60bd80c54f93b/sql/plan/create_index.go#L173
And when the driver went to do the actual index creation in that goroutine, the query had already exited, and the context was cancelled https://github.com/src-d/go-mysql-server/blob/68b087cfd6d30a8d711e1f686da60bd80c54f93b/sql/index/pilosa/driver.go#L419
The first option discussed in slack ([private link](https://src-d.slack.com/archives/C7UDG0GP6/p1571929601195900)) was to change the context of the `createIndex` …

Do not cancel context for async queries on success

---

engine.go
engine_test.go
sql/analyzer/assign_catalog.go
sql/analyzer/assign_catalog_test.go
sql/analyzer/resolve_tables.go
sql/analyzer/resolve_tables_test.go
sql/catalog.go
sql/index.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/parse/util.go
sql/parse/util_test.go
sql/parse/views.go
sql/parse/views_test.go
sql/plan/create_view.go
sql/plan/create_view_test.go
sql/viewregistry.go
sql/viewregistry_test.go

This PR adds basic support for VIEWs. In particular:
- Creation of VIEWs is supported through the syntax `CREATE [OR REPLACE} [db_name.]view_name AS select_expr`
- Views are treated as tables, and when using them in a query, the unresolved table node is replaced with the plan analyzed from the definition of the view.
I wanted to publish this PR as it is because it was getting too big, but the following tasks are still pending for a future PR:
Fixes #53.

Add VIEWs support

---

sql/analyzer/process.go
sql/analyzer/process_test.go
sql/plan/processlist.go
sql/plan/processlist_test.go
sql/processlist.go
sql/processlist_test.go

This is a sugestion by @ajnavarro, related to #855.
With the changes in this PR the output of SHOW PROCESSLIST shows the progress formatted as a tree:
```
mysql> show processlist\G
*************************** 1. row ***************************
Id: 2
User: root
Host: 127.0.0.1:53116
db: gitbase
Command: query
Time: 0
State: running
Info: show processlist
*************************** 2. row ***************************
Id: 1
User: root
Host: 127.0.0.1:53116
db: gitbase
Command: query
Time: 50
State: 
SquashedTable(repositories, commits) (0/3 partitions)
├─ cangallo (101/? rows)
├─ octoprint-tft (101/? rows)
└─ upsilon (101/? rows)
Info: select * from repositories natural join commits
2 rows in set (0.01 sec)
```

Format SHOW PROCESSLIST progress as a tree
