_example/main.go
engine.go
sql/expression/aggregation.go
sql/expression/literal.go
sql/expression/star.go
sql/expression/unresolved.go
sql/parse/parse.go
sql/plan/describe.go
sql/plan/insert.go
sql/plan/show_tables.go
sql/type.go
sql/type_test.go

Also, I cleaned the driver.Driver interface.

sql: MySQL type implementation following the sqltype package 

---

_scripts/go-vitess/Makefile
_scripts/go-vitess/etc/README.md
_scripts/go-vitess/etc/doc.go

Makefile used to generate the `go-vitess` package.

scripts: go-vitess package generator

---

sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/common_test.go
sql/plan/limit.go
sql/plan/limit_test.go
sql/plan/offset.go
sql/plan/offset_test.go

Implements the offset node as a separate node

sql: implement offset node

---

sql/expression/aggregation.go
sql/expression/alias.go
sql/expression/boolean.go
sql/expression/common.go
sql/expression/comparison.go
sql/expression/get_field.go
sql/expression/isnull.go
sql/expression/literal.go
sql/expression/star.go
sql/expression/unresolved.go

Some comments were saying they implemented a different interface

sql/expression: fix docs

---

_scripts/go-vitess/Makefile

It adds a couple of rules to replace glog with logrus.

go-vitess: replace glog with logrus

---

sql/analyzer/rules.go
sql/expression/common.go
sql/functionregistry.go
sql/functionregistry_test.go

sql: implement type-safe function arity

---

sql/parse/parse.go
sql/parse/parse_test.go

sql/parse: support sqlparser.ParenExpr

---

sql/expression/logic.go
sql/expression/logic_test.go
sql/parse/parse.go
sql/parse/parse_test.go

Fixes #40 
Implements both And and Or operators.

sql: implement logic operators

---

sql/expression/common.go
sql/expression/function.go
sql/expression/function_test.go

 sql/expression: implement is_binary UDF 

---

sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/tablealias.go
sql/plan/tablealias_test.go

sql: implement table aliases and subqueries as tables

---

sql/type.go
sql/type_test.go

sql: implement Date type

---

sql/expression/aggregation.go
sql/expression/aggregation_test.go
sql/expression/common.go

MIN aggregation

---

sql/parse/parse.go
sql/parse/parse_test.go

sql/parse: add support for NOT REGEXP operator

---

engine_test.go
sql/expression/between.go
sql/expression/between_test.go
sql/expression/boolean.go
sql/parse/parse.go
sql/parse/parse_test.go

Closes #62 
Since the NOT BETWEEN is in the same parser node, i implemented it as well for just a tiny extra effort.

sql/expression: implement between and not between

---

sql/expression/aggregation.go
sql/expression/aggregation_test.go
sql/expression/boolean_test.go
sql/expression/comparison.go
sql/expression/function.go
sql/expression/function_test.go
sql/expression/logic.go
sql/expression/logic_test.go

sql/expression: correctly handle nulls in all expressions

---

sql/expression/aggregation.go
sql/expression/aggregation_test.go
sql/expression/common.go

MAX aggregation

---

sql/expression/aggregation.go
sql/expression/aggregation_test.go
sql/expression/common.go

AVG aggregation

---

README.md

When #69 will be merged, we can add the AVG to the available function in the README.

Added AVG aggregation to README

---

README.md
engine_test.go
sql/expression/common.go
sql/expression/function.go
sql/expression/function_test.go
sql/expression/function_time.go
sql/expression/function_time_test.go
sql/type.go
sql/type_test.go

Month function is necessary to run the testing queries.

Some Time Functions

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/analyzer/validation_rules.go
sql/analyzer/validation_rules_test.go
sql/core.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/subqueryalias.go
sql/plan/subqueryalias_test.go
sql/plan/tablealias.go
sql/plan/tablealias_test.go

sql/(plan,analyzer): resolve subqueries and groupby validation

---

server/handler.go
server/handler_test.go

handler: stream rows in batches

---

sql/analyzer/filters.go
sql/analyzer/filters_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/expression/logic.go
sql/expression/logic_test.go
sql/plan/pushdown.go

 sql/(plan,analyzer): fix filter and column pushdown 

---

sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/expression/star.go
sql/parse/parse.go
sql/parse/parse_test.go

sql/(parse,analyzer): support qualified Star expressions

---

server/handler.go
server/handler_test.go

Implement kill query

---

sql/expression/function/arraylength.go
sql/expression/function/arraylength_test.go
sql/expression/function/registry.go
sql/type.go

sql/expression: implement array_length UDF

---

sql/plan/pushdown.go

Required by the join pushdown in gitquery.

sql/plan: expose pushdown node fields

---

server/handler.go
server/handler_test.go

Fix unexpected error when an empty set is returned

---

sql/type.go
sql/type_test.go

Fix literal comparison with columns

---

.gitignore
sql/expression/alias.go
sql/expression/between.go
sql/expression/boolean.go
sql/expression/common.go
sql/expression/function/aggregation/avg.go
sql/expression/function/aggregation/count.go
sql/expression/function/aggregation/max.go
sql/expression/function/aggregation/min.go
sql/expression/function/arraylength.go
sql/expression/function/isbinary.go
sql/expression/function/substring.go
sql/expression/function/time.go
sql/expression/literal.go
sql/expression/logic.go
sql/expression/star.go
sql/expression/unresolved.go

I believe all fixes are just typos with missed pointers - PTAL

Fixes - add missed pointers

---

Gopkg.lock
sql/expression/arithmetic.go
sql/expression/arithmetic_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/type.go

https://github.com/src-d/go-mysql-server/issues/142

Support arithmetic operators 

---

README.md
_example/main.go

Updates in README:
- Added expression, functions and statement that are implemented now.
- Added examples.
Also `_example/main.go` has been updated to work properly.
Closes #156

Improve README

---

sql/expression/function/concat.go
sql/expression/function/concat_test.go
sql/expression/function/split.go
sql/expression/function/split_test.go

I implemented concat thinking what @smola meant in the Q9 of the gitbase queries was a concat, but turns out it wasn't. In any case, since it's already done i thought i'd pr it anyway.

sql/expression/function: add concat and split functions

---

LICENSE
README.md

Partly solves: https://github.com/src-d/gitbase/issues/244

license: relicense code as Apache 2.0

---

sql/core.go
sql/index.go

sql: implement index interfaces

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go

sql/analyzer: ensure Star expression is resolved on GroupBy node

---

.travis.yml
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/index.go
sql/index_test.go

 sql/analyzer: support multi-column indexes in assign_indexes 

---

mem/table_test.go
sql/analyzer/analyzer_test.go
sql/functionregistry_test.go
sql/index/config.go
sql/index/config_test.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/mapping_test.go
sql/plan/cross_join_test.go
sql/plan/describe_test.go
sql/plan/distinct_test.go
sql/plan/filter_test.go
sql/plan/limit_test.go
sql/plan/project_test.go
sql/plan/show_tables_test.go
sql/type_test.go

sql/index: auto delete corrupted indexes

---

README.md

readme: add scope, motivation and goals to README

---

sql/plan/create_index.go

sql/(index,plan): add logs for index creation

---

SUPPORTED.md
engine_test.go
sql/expression/function/aggregation/sum.go
sql/expression/function/aggregation/sum_test.go
sql/expression/function/registry.go

sql/function/aggregation: add SUM aggregation function

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go

sql/analyzer: rule to move join conditions to filters

---

sql/index.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/index_test.go
sql/index/pilosa/mapping.go

sql/driver/pilosa: implement AscendIndex and DescendIndex

---

sql/index/pilosa/driver.go
sql/index/pilosa/index.go
sql/index/pilosa/mapping.go
sql/plan/create_index.go
sql/plan/create_index_test.go

@erizocosmico - PTAL if it really makes sense. 
It should fix https://github.com/src-d/go-mysql-server/issues/238, but maybe there is a simpler/nicer fix.

Evaluate expression for index iterator.

---

sql/index/pilosa/driver_test.go

sql/index/pilosa: fix TestPilosaHiccup random failures

---

engine_test.go
sql/analyzer/rules.go
sql/index/pilosa/driver_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/sort.go

sql/parse: fix order by with group by

---

sql/plan/drop_index.go

Closes: https://github.com/src-d/gitbase/issues/349

Fix drop index panic

---

sql/expression/function/time.go
sql/expression/function/time_test.go

Partly solves https://github.com/src-d/gitbase/issues/359

sql/function: make time functions not return errors on conversion

---

engine.go

engine: Register default functions on New(...) constructor too

---

README.md
engine_test.go
sql/expression/function/registry.go

functions: Add CONCAT(...) function.

---

README.md

README: add indexes section

---

sql/analyzer/rules_test.go

sql/analyzer: add tests to ensure deviating behaviour regarding stars

---

engine_test.go
sql/analyzer/rules_test.go
sql/index.go
sql/index_test.go
sql/plan/create_index.go
sql/plan/create_index_test.go
sql/plan/drop_index_test.go

sql/plan: allow synchronous index creations

---

engine_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/expression/between.go

sql/analyzer: resolve ascend and descend indexes

---

sql/expression/function/aggregation/avg.go
sql/expression/function/aggregation/avg_test.go

sql/expression/function/aggregation: allow conversion in AVG

---

engine.go

Partly solves https://github.com/src-d/gitbase/issues/321

sqle: log query in debug

---

sql/plan/create_index.go
sql/plan/create_index_test.go

Closes https://github.com/src-d/gitbase/issues/385

sql/plan: disallow indexes on blob and json columns

---

engine_test.go
sql/analyzer/aggregations.go
sql/analyzer/aggregations_test.go
sql/analyzer/optimization_rules.go
sql/analyzer/rules.go
sql/parse/parse.go
sql/parse/parse_test.go

Closes https://github.com/src-d/gitbase/issues/378

sql/analyzer: add rule to reorder aggregations inside projections

---

engine_test.go

sqle: add tests checking the rule to merge indexes works

---

sql/analyzer/resolve_natural_joins.go
sql/analyzer/resolve_natural_joins_test.go

Partial fix for https://github.com/src-d/gitbase/issues/388
Related to https://github.com/src-d/gitbase/pull/391

sql/analyzer: fix resolveNaturalJoins rule to work properly with table aliases

---

sql/index/pilosalib/driver.go

Fix LoadAll when .pilosa doesn't exist.

---

sql/plan/show_indexes.go
sql/plan/show_indexes_test.go

Closes #315 
Now the information returned is more accurate. It shows the columns indexed for each index or if what the indexed thing is an expression.
```
MySQL [(none)]> show indexes from files;
+-------+------------+---------------------+--------------+---------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+-------------------------------+
| Table | Non_unique | Key_name            | Seq_in_index | Column_name         | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression                    |
+-------+------------+---------------------+--------------+---------------------+-----------+-------------+----------+--------+------+------------+---------+--------------- …
```

sql/plan: improve information returned by show indexes

---

sql/index/config.go
sql/index/config_test.go
sql/index/pilosalib/driver.go
sql/index/pilosalib/driver_test.go

Related to https://github.com/src-d/gitbase/issues/411
Approach coming from https://github.com/src-d/go-mysql-server/pull/318

sql/index/pilosalib: create processing file on index creation

---

sql/index/pilosa/driver_test.go
sql/index/pilosa/lookup.go
sql/index/pilosalib/driver_test.go
sql/index/pilosalib/lookup.go

Closes https://github.com/src-d/go-mysql-server/issues/323

Fix "NOT expressions with non existing value"

---

SUPPORTED.md

SUPPORTED.md: add show indexes syntax to the supported index expressions

---

sql/index/pilosalib/driver.go
sql/index/pilosalib/mapping.go

Should Fix: https://github.com/src-d/gitbase/issues/415

Fix bitBatch.Clean in pilosalib

---

sql/analyzer/assign_indexes_test.go
sql/analyzer/pushdown_test.go
sql/index.go
sql/index/pilosa/lookup.go
sql/index/pilosa/lookup_test.go
sql/index/pilosalib/lookup.go
sql/index/pilosalib/lookup_test.go
sql/plan/pushdown.go
sql/plan/pushdown_test.go

*: make IndexLookup return index IDs

---

go.mod

Add support for go modules.

---

.travis.yml
Makefile

Also fixes sending tags to go compiler with new CI system.

travis: execute ci-script to test and send coverage

---

.travis.yml
README.md
go.mod
sql/index/pilosa/driver.go
sql/index/pilosa/index.go
sql/index/pilosa/lookup.go
sql/index/pilosa/lookup_test.go

Closes https://github.com/src-d/go-mysql-server/issues/353
We're up to date now 😎

sql/index/pilosa: upgrade to go-pilosa v0.10.0 and migrate API

---

sql/index/pilosa/driver.go
sql/index/pilosalib/driver.go

Fixes https://github.com/src-d/go-mysql-server/issues/364

Fix potential data race

---

sql/index/pilosalib/driver.go

fix compilation error on master.

---

engine_test.go
sql/expression/function/concat.go
sql/plan/set.go
sql/session.go

Fixes for #361. It was merged before I could push this 😅

sql/*: fix small issues to make Set resolve correctly

---

engine_test.go
sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go
sql/analyzer/rules.go

Closes https://github.com/src-d/gitbase/issues/460

sql/analyzer: resolve aggregate aliases in groupby grouping

---

README.md
sql/plan/create_index.go
sql/plan/create_index_test.go

Closes https://github.com/src-d/gitbase/issues/478
Don't merge yet, still need to test about how it handles connection drops.

sql/plan: make create index sync by default

---

engine_test.go
sql/analyzer/parallelize_test.go
sql/analyzer/rules.go

Fixes https://github.com/src-d/gitbase/pull/486

sql/analyzer: execute parallelize as last rule

---

sql/analyzer/resolve_tables_test.go
sql/catalog.go
sql/catalog_test.go

sql: make table resolution case insensitive

---

sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go
sql/plan/set.go

Related to: https://github.com/src-d/gitbase/issues/510

Fix get/set from global table.

---

engine_test.go
sql/analyzer/resolve_columns.go

Related to: https://github.com/src-d/gitbase/issues/500

If deferredColumns is an alias then resolve it.

---

sql/type.go

sql: give types a String method

---

go.mod
sql/expression/function/ceil_round_floor.go
sql/expression/function/ceil_round_floor_test.go
sql/expression/function/registry.go

Signed-off-by: Theodoros Zarkopafilis Ntakouris <zarkopafilis@gmail.com>

sql: expression: function: Add CEIL, CEILING, FLOOR, ROUND. [Fixes #393]

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/nothing.go

sql/parse: strip comments from queries

---

engine_test.go
sql/analyzer/assign_catalog.go
sql/analyzer/assign_catalog_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/showdatabases.go

sql: implement SHOW DATABASES

---

go.mod
sql/expression/function/lower_upper.go
sql/expression/function/lower_upper_test.go
sql/expression/function/registry.go

#390 
Signed-off-by: Zarkopafilis <zarkopafilis@gmail.com>

sql: expression: function: Add LOWER, UPPER [Fix #390]

---

engine_test.go
sql/expression/like.go
sql/expression/like_test.go
sql/parse/parse.go
sql/parse/parse_test.go

Closes https://github.com/src-d/go-mysql-server/issues/426

sql: implement LIKE expression

---

README.md
SUPPORTED.md

Add missing functions to documentation.

---

engine.go
engine_test.go
mem/table.go
mem/table_test.go
sql/analyzer/analyzer.go
sql/analyzer/analyzer_test.go
sql/analyzer/assign_catalog.go
sql/analyzer/assign_catalog_test.go
sql/analyzer/assign_indexes.go
sql/analyzer/pushdown_test.go
sql/analyzer/resolve_database.go
sql/analyzer/resolve_subqueries_test.go
sql/analyzer/resolve_tables.go
sql/analyzer/resolve_tables_test.go
sql/catalog.go
sql/catalog_test.go
sql/parse/indexes.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/create_index_test.go
sql/plan/ddl.go
sql/plan/drop_index_test.go
sql/plan/show_indexes.go
sql/plan/show_indexes_test.go
sql/plan/show_tables.go
sql/plan/show_tables_test.go
sql/plan/showdatabases.go
sql/plan/showtablestatus.go
sql/plan/use.go
sql/unresolved_database.go

Closes #411 
- Implement USE
- Change implementation of UnresolvedDatabase
- Catalog is not thread-safe
- CurrentDatabase is now on the Catalog

sql: implement USE <table> statement

---

engine_test.go
sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go

sql/analyzer: fix ambiguous table after natural join

---

engine_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/resolve_subqueries_test.go
sql/analyzer/resolve_tables.go
sql/analyzer/resolve_tables_test.go
sql/parse/describe_test.go
sql/parse/indexes.go
sql/parse/indexes_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/describe_test.go
sql/plan/transform_test.go
sql/plan/unresolved.go
sql/plan/unresolved_test.go
sql/plan/walk_test.go

 sql: resolve tables with database qualifier

---

sql/expression/function/ceil_round_floor.go

Fixes #443 
Signed-off-by: Theodoros Zarkopafilis Ntakouris <zarkopafilis@gmail.com>

sql: expression: function: ROUND Panic fix (typo) (Fix 443)

---

sql/expression/function/ceil_round_floor.go
sql/expression/function/ceil_round_floor_test.go

function: handle non number arguments in ceil, floor and round

---

engine_test.go
sql/expression/function/json_extract.go
sql/expression/function/json_extract_test.go
sql/expression/function/registry.go

function: implement JSON_EXTRACT UDF

---

sql/analyzer/process.go
sql/analyzer/process_test.go
sql/plan/create_index.go
sql/plan/insert.go
sql/plan/process.go
sql/plan/process_test.go

sql/(plan,analyzer): track partitions of indexable tables too

---

.travis.yml

Trying to see if this fixes the java build

[WIP] travis: use jdk9 instead

---

engine_test.go
sql/analyzer/resolve_database.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/parse/show_create.go
sql/plan/show_create_database.go
sql/plan/show_create_database_test.go

sql: implement SHOW CREATE DATABASE statement

---

LICENSE

Solves #476 
Added the org name and year in license

update license with year and org name

---

sql/plan/group_by.go
sql/plan/group_by_test.go

Fixes: https://github.com/src-d/go-mysql-server/issues/481

Check if eval buffer is empty.

---

sql/parse/parse.go
sql/parse/parse_test.go

Add support for using `desc table`.
Closes #494

Add support for using desc table

---

engine.go
engine_test.go
sql/expression/function/database.go

Closes: https://github.com/src-d/go-mysql-server/issues/503

Implement DATABASE() function.

---

engine_test.go
sql/information_schema.go

Closes: https://github.com/src-d/go-mysql-server/issues/510

Add support for information_schema.columns

---

LICENSE

Reverts src-d/go-mysql-server#475

Revert "update license with year and org name"

---

go.mod

go-vitess@1.3.0

---

engine_test.go
sql/information_schema.go

sql: add information_schema.schemata table

---

SUPPORTED.md

docs: add missing supported expressions

---

sql/expression/function/registry.go
sql/expression/function/trim_ltrim_rtrim.go
sql/expression/function/trim_ltrim_rtrim_test.go

Signed-off-by: Theo Despoudis <thdespou@hotmail.com>
Trim only supports basic grammar but I've referenced a feature request in vitess:
https://github.com/vitessio/vitess/issues/4347

Add Trim, Ltrim, Rtrim

---

.travis.yml
README.md

docs: add go-vitess dependency information

---

engine_test.go
go.mod
sql/expression/function/registry.go
sql/expression/function/reverse_repeat_replace.go
sql/expression/function/reverse_repeat_replace_test.go
sql/parse/parse.go

Signed-off-by: Theo Despoudis <thdespou@hotmail.com>

Add Reverse, Repeat, Replace

---

SUPPORTED_CLIENTS.md

docs: add tableau to supported clients

---

sql/analyzer/analyzer_test.go
sql/analyzer/optimization_rules.go

Closes https://github.com/src-d/gitbase/issues/643

analyzer: wait until NaturalJoins are resolved on reorder rule

---

engine_test.go
go.mod
sql/expression/function/ceil_round_floor.go
sql/expression/function/ceil_round_floor_test.go

Fixes https://github.com/src-d/engine/issues/168
Closes https://github.com/src-d/go-mysql-server/issues/579

Fix ROUND function for 2 args.

---

auth/common_test.go
engine_test.go
mem/table.go
mem/table_test.go
sql/analyzer/aggregations.go
sql/analyzer/assign_catalog.go
sql/analyzer/assign_indexes.go
sql/analyzer/optimization_rules.go
sql/analyzer/resolve_columns.go
sql/analyzer/resolve_columns_test.go
sql/analyzer/resolve_database.go
sql/analyzer/resolve_functions.go
sql/analyzer/resolve_natural_joins.go
sql/analyzer/resolve_orderby.go
sql/analyzer/resolve_stars.go
sql/analyzer/resolve_tables.go
sql/analyzer/validation_rules.go
sql/expression/function/ceil_round_floor_test.go
sql/index.go
sql/index/pilosa/driver.go
sql/index/pilosa/driver_test.go
sql/index/pilosa/index.go
sql/index/pilosa/lookup.go
sql/plan/create_index.go
sql/plan/limit.go
sql/plan/set.go
sql/plan/show_create_table.go
sql/plan/showcolumns.go
sql/type.go

fix errors pointed out by staticcheck

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/transaction.go

sql: implement dummy ROLLBACK

---

sql/plan/create_index.go
sql/plan/create_index_test.go

Fixes https://github.com/src-d/go-mysql-server/issues/612

Fix checksum for multi underlying tables.

---

engine_test.go
sql/analyzer/prune_columns.go

fix prune columns for describe queries

---

engine_test.go

Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

Fix test error after two PR merges.

---

README.md
sql/plan/innerjoin.go

 docs: add session and environment variables to README

---

.travis.yml
sql/index/pilosa/driver.go

pilosa: set max map count to 0 to avoid index issues on windows

---

engine_test.go
sql/expression/function/registry.go
sql/expression/function/substring.go
sql/expression/function/substring_test.go

Based on:
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index
Closes: https://github.com/src-d/go-mysql-server/issues/716

Implement SUBSTRING_INDEX UDF

---

engine_test.go
go.mod
go.sum

Upgrade vitess to v1.7.0

---

engine_test.go
sql/analyzer/validation_rules.go
sql/expression/case.go
sql/expression/case_test.go

sql/expression: allow null literals in case branches

---

go.mod
go.sum
sql/analyzer/resolve_natural_joins.go
sql/plan/exchange.go

Now it's more simple, easier to understand and has way less code.

sql/analyzer: refactor resolve_natural_joins rule

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go

Fixes https://github.com/src-d/gitbase/issues/869

sql/parse: error for unsupported distinct on aggregations

---

engine_test.go
sql/expression/arithmetic.go

sql/expression: handle null values in arithmetic expressions

---

server/context.go

server: start root trace span on context creation

---

README.md
engine_test.go
sql/analyzer/resolve_having.go
sql/expression/function/aggregation/common_test.go
sql/expression/function/aggregation/first.go
sql/expression/function/aggregation/first_test.go
sql/expression/function/aggregation/last.go
sql/expression/function/aggregation/last_test.go
sql/expression/function/registry.go
sql/parse/parse.go
sql/parse/parse_test.go

sql: implement FIRST and LAST aggregation functions

---

engine_test.go
sql/analyzer/resolve_orderby.go

Will fix https://github.com/src-d/gitbase/issues/937 when it's updated.

sql/analyzer: fix order by resolution for all nodes

---

.travis.yml

use goproxy

---

README.md

We've been migrating our SQL implementation from an in-house version to this one. I just noticed that you guys have a _Powered by_ section, and thought it would be cool to be included in there. 😄

Add dolt to README

---

.travis.yml
_integration/javascript/package-lock.json
_integration/javascript/package.json

Fix a security alert in set-value, one of the dependencies of ava.
Signed-off-by: Alejandro García Montoro <alejandro.garciamontoro@gmail.com>

Bump ava version

---

_integration/javascript/package-lock.json
_integration/javascript/package.json

fix missing module in node integration test

---

CODEOWNERS
MAINTAINERS

Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

Modify MAINTAINERS and added CODEWONERS

---

sql/index/config.go
sql/index/pilosa/driver.go

Related to https://github.com/src-d/gitbase/issues/971

sql/index/pilosa: better error messages

---

sql/plan/show_create_table_test.go
sql/type.go

sql: Add length to VARCHAR MySQLTypeName string

---

sql/plan/show_create_table_test.go
sql/type.go

sql: Add length to CHAR MySQLTypeName string
